// icon.types.ts — AUTO-GENERATED by scripts/generate-sprite.cjs
// DO NOT EDIT MANUALLY. Re-run: pnpm prep:icons
// Generated: 2026-09-03T00:16:58.677Z
// Total: 1897 (919 linear + 978 bold)

export type LinearIconName =
  'linear-24-support'
  | 'linear-3d-cube-scan'
  | 'linear-3d-rotate'
  | 'linear-3d-square'
  | 'linear-3dcube'
  | 'linear-3square'
  | 'linear-aave'
  | 'linear-activity'
  | 'linear-add-circle'
  | 'linear-add-square'
  | 'linear-add'
  | 'linear-additem'
  | 'linear-airdrop'
  | 'linear-airplane-square'
  | 'linear-airplane'
  | 'linear-airpod'
  | 'linear-airpods'
  | 'linear-alarm'
  | 'linear-align-bottom'
  | 'linear-align-horizontally'
  | 'linear-align-left'
  | 'linear-align-right'
  | 'linear-align-vertically'
  | 'linear-android'
  | 'linear-ankr'
  | 'linear-apple'
  | 'linear-aquarius'
  | 'linear-archive-add'
  | 'linear-archive-book'
  | 'linear-archive-minus'
  | 'linear-archive-slash'
  | 'linear-archive-tick'
  | 'linear-archive'
  | 'linear-arrange-circle-2'
  | 'linear-arrange-circle'
  | 'linear-arrange-square-2'
  | 'linear-arrange-square'
  | 'linear-arrow-2'
  | 'linear-arrow-3'
  | 'linear-arrow-bottom'
  | 'linear-arrow-circle-down'
  | 'linear-arrow-circle-left'
  | 'linear-arrow-circle-right'
  | 'linear-arrow-down-1'
  | 'linear-arrow-down-2'
  | 'linear-arrow-down'
  | 'linear-arrow-left-1'
  | 'linear-arrow-left-2'
  | 'linear-arrow-left-3'
  | 'linear-arrow-left'
  | 'linear-arrow-right-1'
  | 'linear-arrow-right-2'
  | 'linear-arrow-right-3'
  | 'linear-arrow-right'
  | 'linear-arrow-square-down'
  | 'linear-arrow-square-left'
  | 'linear-arrow-square-right'
  | 'linear-arrow-square-up'
  | 'linear-arrow-square'
  | 'linear-arrow-swap-horizontal'
  | 'linear-arrow-up-1'
  | 'linear-arrow-up-2'
  | 'linear-arrow-up-3'
  | 'linear-arrow-up'
  | 'linear-arrow'
  | 'linear-attach-circle'
  | 'linear-attach-square'
  | 'linear-augur'
  | 'linear-autobrightness'
  | 'linear-autonio'
  | 'linear-avalanche'
  | 'linear-award'
  | 'linear-back-square'
  | 'linear-backward-item-1'
  | 'linear-backward-item'
  | 'linear-bag-2'
  | 'linear-bag-cross-1'
  | 'linear-bag-cross'
  | 'linear-bag-happy'
  | 'linear-bag-tick-2'
  | 'linear-bag-tick'
  | 'linear-bag-timer'
  | 'linear-bag'
  | 'linear-bank'
  | 'linear-barcode'
  | 'linear-battery-charging'
  | 'linear-battery-disable'
  | 'linear-battery-empty-1'
  | 'linear-battery-empty'
  | 'linear-battery-full'
  | 'linear-be'
  | 'linear-bezier-1'
  | 'linear-bezier'
  | 'linear-bill'
  | 'linear-binance-coin'
  | 'linear-binance-usd'
  | 'linear-bitcoin'
  | 'linear-bitcoin-card'
  | 'linear-bitcoin-convert'
  | 'linear-bitcoin-refresh'
  | 'linear-blend-2'
  | 'linear-blend'
  | 'linear-blogger'
  | 'linear-bluetooth-2'
  | 'linear-bluetooth-circle'
  | 'linear-bluetooth-rectangle'
  | 'linear-bluetooth'
  | 'linear-blur-1'
  | 'linear-blur'
  | 'linear-book-1'
  | 'linear-book-saved'
  | 'linear-book-square'
  | 'linear-book'
  | 'linear-bookmark-2'
  | 'linear-bookmark'
  | 'linear-bootsrap'
  | 'linear-box-1'
  | 'linear-box-2'
  | 'linear-box-add'
  | 'linear-box-remove'
  | 'linear-box-search'
  | 'linear-box-tick'
  | 'linear-box-time'
  | 'linear-box'
  | 'linear-briefcase'
  | 'linear-brifecase-cross'
  | 'linear-brifecase-tick'
  | 'linear-brifecase-timer'
  | 'linear-broom'
  | 'linear-brush-1'
  | 'linear-brush-2'
  | 'linear-brush-3'
  | 'linear-brush'
  | 'linear-bubble'
  | 'linear-bucket-circle-1'
  | 'linear-bucket-circle'
  | 'linear-bucket-square-1'
  | 'linear-bucket-square'
  | 'linear-building-3'
  | 'linear-building-4'
  | 'linear-building'
  | 'linear-buildings-2'
  | 'linear-buildings'
  | 'linear-buliding'
  | 'linear-bus'
  | 'linear-buy-crypto'
  | 'linear-cake'
  | 'linear-calculator'
  | 'linear-calendar-1'
  | 'linear-calendar-2'
  | 'linear-calendar-add'
  | 'linear-calendar-circle'
  | 'linear-calendar-edit'
  | 'linear-calendar-remove'
  | 'linear-calendar-search'
  | 'linear-calendar-tick'
  | 'linear-calendar'
  | 'linear-call-add'
  | 'linear-call-calling'
  | 'linear-call-incoming'
  | 'linear-call-minus'
  | 'linear-call-outgoing'
  | 'linear-call-received'
  | 'linear-call-remove'
  | 'linear-call-slash'
  | 'linear-call'
  | 'linear-candle-2'
  | 'linear-candle'
  | 'linear-car'
  | 'linear-card-add'
  | 'linear-card-coin'
  | 'linear-card-edit'
  | 'linear-card-pos'
  | 'linear-card-receive'
  | 'linear-card-remove-1'
  | 'linear-card-remove'
  | 'linear-card-send'
  | 'linear-card-slash'
  | 'linear-card-tick-1'
  | 'linear-card-tick'
  | 'linear-card'
  | 'linear-cardano'
  | 'linear-cards'
  | 'linear-category-2'
  | 'linear-category'
  | 'linear-cd'
  | 'linear-celo'
  | 'linear-celsius'
  | 'linear-chainlink'
  | 'linear-chart-1'
  | 'linear-chart-2'
  | 'linear-chart-21'
  | 'linear-chart-square'
  | 'linear-chart-success'
  | 'linear-chart'
  | 'linear-check'
  | 'linear-chrome'
  | 'linear-civic'
  | 'linear-clipboard-close'
  | 'linear-clipboard-export'
  | 'linear-clipboard-import'
  | 'linear-clipboard-text'
  | 'linear-clipboard-tick'
  | 'linear-clipboard'
  | 'linear-clock-1'
  | 'linear-clock'
  | 'linear-close-circle'
  | 'linear-close-square'
  | 'linear-cloud-add'
  | 'linear-cloud-change'
  | 'linear-cloud-connection'
  | 'linear-cloud-cross'
  | 'linear-cloud-drizzle'
  | 'linear-cloud-fog'
  | 'linear-cloud-lightning'
  | 'linear-cloud-minus'
  | 'linear-cloud-notif'
  | 'linear-cloud-plus'
  | 'linear-cloud-remove'
  | 'linear-cloud-snow'
  | 'linear-cloud-sunny'
  | 'linear-cloud'
  | 'linear-code-1'
  | 'linear-code-circle'
  | 'linear-code'
  | 'linear-coffee'
  | 'linear-coin-1'
  | 'linear-coin'
  | 'linear-color-swatch'
  | 'linear-colorfilter'
  | 'linear-colors-square-1'
  | 'linear-colors-square'
  | 'linear-command-square'
  | 'linear-command'
  | 'linear-component-1'
  | 'linear-component'
  | 'linear-computing'
  | 'linear-convert-3d-cube'
  | 'linear-convert'
  | 'linear-convertshape-2'
  | 'linear-convertshape'
  | 'linear-copy-success'
  | 'linear-copy'
  | 'linear-copyright'
  | 'linear-courthouse'
  | 'linear-cpu-charge'
  | 'linear-cpu-setting'
  | 'linear-cpu'
  | 'linear-creative-commons'
  | 'linear-crop'
  | 'linear-crown-1'
  | 'linear-crown'
  | 'linear-cup'
  | 'linear-dai'
  | 'linear-danger'
  | 'linear-dash'
  | 'linear-data-2'
  | 'linear-data'
  | 'linear-decred'
  | 'linear-dent'
  | 'linear-designtools'
  | 'linear-device-message'
  | 'linear-devices'
  | 'linear-diagram'
  | 'linear-diamonds'
  | 'linear-direct-down'
  | 'linear-direct-inbox'
  | 'linear-direct-left'
  | 'linear-direct-normal'
  | 'linear-direct-notification'
  | 'linear-direct-right'
  | 'linear-direct-send'
  | 'linear-direct-up'
  | 'linear-direct'
  | 'linear-directbox-default'
  | 'linear-directbox-notif'
  | 'linear-directbox-receive'
  | 'linear-directbox-send'
  | 'linear-discount-circle'
  | 'linear-discount-shape'
  | 'linear-discover-1'
  | 'linear-discover'
  | 'linear-dislike'
  | 'linear-document-cloud'
  | 'linear-document-code-2'
  | 'linear-document-code'
  | 'linear-document-copy'
  | 'linear-document-download'
  | 'linear-document-favorite'
  | 'linear-document-filter'
  | 'linear-document-forward'
  | 'linear-document-like'
  | 'linear-document-previous'
  | 'linear-document-sketch'
  | 'linear-document-text-1'
  | 'linear-document-text'
  | 'linear-document-upload'
  | 'linear-document'
  | 'linear-dollar-circle'
  | 'linear-dollar-square'
  | 'linear-dribbble'
  | 'linear-driver-2'
  | 'linear-driver-refresh'
  | 'linear-driver'
  | 'linear-driving'
  | 'linear-drop'
  | 'linear-dropbox'
  | 'linear-edit-2'
  | 'linear-edit'
  | 'linear-educare'
  | 'linear-electricity'
  | 'linear-element-1'
  | 'linear-element-2'
  | 'linear-element-3'
  | 'linear-element-4'
  | 'linear-element-equal'
  | 'linear-element-plus'
  | 'linear-emercoin'
  | 'linear-emoji-happy'
  | 'linear-emoji-normal-1'
  | 'linear-emoji-normal'
  | 'linear-emoji-sad'
  | 'linear-emoji-super'
  | 'linear-empty-wallet-add'
  | 'linear-empty-wallet-change'
  | 'linear-empty-wallet-remove'
  | 'linear-empty-wallet-tick'
  | 'linear-empty-wallet-time'
  | 'linear-empty-wallet'
  | 'linear-enjin-coin'
  | 'linear-eos'
  | 'linear-eraser-1'
  | 'linear-eraser'
  | 'linear-ethereum'
  | 'linear-ethereum-classic'
  | 'linear-export-1'
  | 'linear-export-2'
  | 'linear-export-3'
  | 'linear-export'
  | 'linear-external-drive'
  | 'linear-eye-slash'
  | 'linear-eye'
  | 'linear-facebook'
  | 'linear-fatrows'
  | 'linear-favorite-chart'
  | 'linear-figma-1'
  | 'linear-figma'
  | 'linear-filter-add'
  | 'linear-filter-edit'
  | 'linear-filter-remove'
  | 'linear-filter-search'
  | 'linear-filter-square'
  | 'linear-filter-tick'
  | 'linear-filter'
  | 'linear-finger-cricle'
  | 'linear-finger-scan'
  | 'linear-firstline'
  | 'linear-flag-2'
  | 'linear-flag'
  | 'linear-flash-circle-1'
  | 'linear-flash-circle-2'
  | 'linear-flash-circle'
  | 'linear-flash-slash'
  | 'linear-flash'
  | 'linear-folder-2'
  | 'linear-folder-add'
  | 'linear-folder-cloud'
  | 'linear-folder-connection'
  | 'linear-folder-cross'
  | 'linear-folder-favorite'
  | 'linear-folder-minus'
  | 'linear-folder-open'
  | 'linear-folder'
  | 'linear-format-circle'
  | 'linear-format-square'
  | 'linear-forward-item-1'
  | 'linear-forward-item'
  | 'linear-forward-square'
  | 'linear-frame-1'
  | 'linear-frame-2'
  | 'linear-frame-3'
  | 'linear-frame'
  | 'linear-framer'
  | 'linear-ftx-token'
  | 'linear-game'
  | 'linear-gameboy'
  | 'linear-gas-station'
  | 'linear-gemini-2'
  | 'linear-gemini'
  | 'linear-ghost'
  | 'linear-gift'
  | 'linear-glass-1'
  | 'linear-glass'
  | 'linear-global-edit'
  | 'linear-global-refresh'
  | 'linear-global-search'
  | 'linear-global'
  | 'linear-google-1'
  | 'linear-google-play'
  | 'linear-google'
  | 'linear-gps-slash'
  | 'linear-gps'
  | 'linear-grammerly'
  | 'linear-graph'
  | 'linear-grid-1'
  | 'linear-grid-2'
  | 'linear-grid-3'
  | 'linear-grid-4'
  | 'linear-grid-5'
  | 'linear-grid-6'
  | 'linear-grid-7'
  | 'linear-grid-8'
  | 'linear-grid-9'
  | 'linear-grid-edit'
  | 'linear-grid-eraser'
  | 'linear-grid-lock'
  | 'linear-group-1'
  | 'linear-group-2'
  | 'linear-group-3'
  | 'linear-group-4'
  | 'linear-group-5'
  | 'linear-group-6'
  | 'linear-group-7'
  | 'linear-group-8'
  | 'linear-group'
  | 'linear-happyemoji'
  | 'linear-harmony'
  | 'linear-hashtag-down'
  | 'linear-hashtag-up'
  | 'linear-hashtag'
  | 'linear-headphone'
  | 'linear-headphones'
  | 'linear-health'
  | 'linear-heart-add'
  | 'linear-heart-circle'
  | 'linear-heart-edit'
  | 'linear-heart-remove'
  | 'linear-heart-search'
  | 'linear-heart-slash'
  | 'linear-heart-tick'
  | 'linear-heart'
  | 'linear-hedera-hashgraph'
  | 'linear-hex'
  | 'linear-hierarchy-2'
  | 'linear-hierarchy-3'
  | 'linear-hierarchy-square-2'
  | 'linear-hierarchy-square-3'
  | 'linear-hierarchy-square'
  | 'linear-hierarchy'
  | 'linear-home-2'
  | 'linear-home-hashtag'
  | 'linear-home-trend-down'
  | 'linear-home-trend-up'
  | 'linear-home-wifi'
  | 'linear-home'
  | 'linear-hospital'
  | 'linear-house-2'
  | 'linear-house'
  | 'linear-html-3'
  | 'linear-html-5'
  | 'linear-huobi-token'
  | 'linear-icon'
  | 'linear-illustrator'
  | 'linear-import-1'
  | 'linear-import-2'
  | 'linear-import'
  | 'linear-info-circle'
  | 'linear-information'
  | 'linear-instagram'
  | 'linear-iost'
  | 'linear-java-script'
  | 'linear-js'
  | 'linear-judge'
  | 'linear-kanban'
  | 'linear-key-square'
  | 'linear-key'
  | 'linear-keyboard-open'
  | 'linear-keyboard'
  | 'linear-kyber-network'
  | 'linear-lamp-charge'
  | 'linear-lamp-on'
  | 'linear-lamp-slash'
  | 'linear-lamp'
  | 'linear-language-circle'
  | 'linear-language-square'
  | 'linear-layer'
  | 'linear-level'
  | 'linear-lifebuoy'
  | 'linear-like-1'
  | 'linear-like-dislike'
  | 'linear-like-shapes'
  | 'linear-like-tag'
  | 'linear-like'
  | 'linear-link-1'
  | 'linear-link-2'
  | 'linear-link-21'
  | 'linear-link-circle'
  | 'linear-link-square'
  | 'linear-link'
  | 'linear-litecoin'
  | 'linear-location-add'
  | 'linear-location-cross'
  | 'linear-location-minus'
  | 'linear-location-slash'
  | 'linear-location-tick'
  | 'linear-location'
  | 'linear-lock-1'
  | 'linear-lock-circle'
  | 'linear-lock-slash'
  | 'linear-lock'
  | 'linear-login-1'
  | 'linear-login'
  | 'linear-logout-1'
  | 'linear-logout'
  | 'linear-lovely'
  | 'linear-magic-star'
  | 'linear-magicpen'
  | 'linear-main-component-1'
  | 'linear-main-component'
  | 'linear-maker'
  | 'linear-man'
  | 'linear-map-1'
  | 'linear-map'
  | 'linear-mask-1'
  | 'linear-mask-2'
  | 'linear-mask-3'
  | 'linear-mask'
  | 'linear-math'
  | 'linear-maximize-1'
  | 'linear-maximize-2'
  | 'linear-maximize-3'
  | 'linear-maximize-4'
  | 'linear-maximize'
  | 'linear-medal-star'
  | 'linear-medal'
  | 'linear-menu-board'
  | 'linear-menu'
  | 'linear-message-2'
  | 'linear-message-add-1'
  | 'linear-message-add'
  | 'linear-message-circle'
  | 'linear-message-edit'
  | 'linear-message-favorite'
  | 'linear-message-minus'
  | 'linear-message-notif'
  | 'linear-message-programming'
  | 'linear-message-question'
  | 'linear-message-remove'
  | 'linear-message-search'
  | 'linear-message-square'
  | 'linear-message-text-1'
  | 'linear-message-text'
  | 'linear-message-tick'
  | 'linear-message-time'
  | 'linear-message'
  | 'linear-messages-1'
  | 'linear-messages-2'
  | 'linear-messages-3'
  | 'linear-messages'
  | 'linear-messenger'
  | 'linear-microscope'
  | 'linear-milk'
  | 'linear-minus-cirlce'
  | 'linear-minus-square'
  | 'linear-minus'
  | 'linear-mirror'
  | 'linear-mirroring-screen'
  | 'linear-mobile-programming'
  | 'linear-mobile'
  | 'linear-monero'
  | 'linear-money-2'
  | 'linear-money-3'
  | 'linear-money-4'
  | 'linear-money-add'
  | 'linear-money-change'
  | 'linear-money-forbidden'
  | 'linear-money-recive'
  | 'linear-money-remove'
  | 'linear-money-send'
  | 'linear-money-tick'
  | 'linear-money-time'
  | 'linear-money'
  | 'linear-moneys'
  | 'linear-monitor-mobbile'
  | 'linear-monitor-recorder'
  | 'linear-monitor'
  | 'linear-moon'
  | 'linear-more-2'
  | 'linear-more-circle'
  | 'linear-more-square'
  | 'linear-more'
  | 'linear-mouse-circle'
  | 'linear-mouse-square'
  | 'linear-mouse'
  | 'linear-music-play'
  | 'linear-nebulas'
  | 'linear-nem'
  | 'linear-nexo'
  | 'linear-note-1'
  | 'linear-note-2'
  | 'linear-note-21'
  | 'linear-note-add'
  | 'linear-note-favorite'
  | 'linear-note-remove'
  | 'linear-note-text'
  | 'linear-note'
  | 'linear-notification-1'
  | 'linear-notification-bing'
  | 'linear-notification-circle'
  | 'linear-notification-favorite'
  | 'linear-notification-status'
  | 'linear-notification'
  | 'linear-ocean-protocol'
  | 'linear-okb'
  | 'linear-omega-circle-1'
  | 'linear-omega-circle'
  | 'linear-omega-square-1'
  | 'linear-omega-square'
  | 'linear-ontology'
  | 'linear-paintbucket'
  | 'linear-paperclip-2'
  | 'linear-paperclip'
  | 'linear-password-check'
  | 'linear-path-2'
  | 'linear-path-square'
  | 'linear-path'
  | 'linear-paypal'
  | 'linear-pen-add-1'
  | 'linear-pen-add'
  | 'linear-pen-close-1'
  | 'linear-pen-close'
  | 'linear-pen-remove-1'
  | 'linear-pen-remove'
  | 'linear-pen-tool-1'
  | 'linear-pen-tool-2-1'
  | 'linear-pen-tool-2'
  | 'linear-pen-tool'
  | 'linear-people'
  | 'linear-percentage-square'
  | 'linear-personalcard'
  | 'linear-pet'
  | 'linear-pharagraphspacing'
  | 'linear-photoshop'
  | 'linear-picture-frame'
  | 'linear-polkadot'
  | 'linear-polygon'
  | 'linear-polyswarm'
  | 'linear-presention-chart'
  | 'linear-printer-slash'
  | 'linear-printer'
  | 'linear-profile-2user'
  | 'linear-profile-add'
  | 'linear-profile-circle'
  | 'linear-profile-delete'
  | 'linear-profile-remove'
  | 'linear-profile-tick'
  | 'linear-profile'
  | 'linear-programming-arrow'
  | 'linear-programming-arrows'
  | 'linear-python'
  | 'linear-quant'
  | 'linear-quote-down-circle'
  | 'linear-quote-down-square'
  | 'linear-quote-down'
  | 'linear-quote-up-circle'
  | 'linear-quote-up-square'
  | 'linear-quote-up'
  | 'linear-radar-1'
  | 'linear-radar-2'
  | 'linear-radar'
  | 'linear-ram-2'
  | 'linear-ram'
  | 'linear-ranking-1'
  | 'linear-ranking'
  | 'linear-receipt-1'
  | 'linear-receipt-2-1'
  | 'linear-receipt-2'
  | 'linear-receipt-add'
  | 'linear-receipt-discount'
  | 'linear-receipt-disscount'
  | 'linear-receipt-edit'
  | 'linear-receipt-item'
  | 'linear-receipt-minus'
  | 'linear-receipt-search'
  | 'linear-receipt-square'
  | 'linear-receipt-text'
  | 'linear-receipt'
  | 'linear-receive-square-2'
  | 'linear-receive-square'
  | 'linear-received'
  | 'linear-recovery-convert'
  | 'linear-redo'
  | 'linear-refresh-2'
  | 'linear-refresh-circle'
  | 'linear-refresh-left-square'
  | 'linear-refresh-right-square'
  | 'linear-refresh-square-2'
  | 'linear-refresh'
  | 'linear-repeat-circle'
  | 'linear-repeat'
  | 'linear-reserve'
  | 'linear-rotate-left'
  | 'linear-rotate-right'
  | 'linear-route-square'
  | 'linear-routing-2'
  | 'linear-routing'
  | 'linear-row-horizontal'
  | 'linear-row-vertical'
  | 'linear-rulerpen'
  | 'linear-ruler'
  | 'linear-safe-home'
  | 'linear-sagittarius'
  | 'linear-save-2'
  | 'linear-save-add'
  | 'linear-save-minus'
  | 'linear-save-remove'
  | 'linear-scan-barcode'
  | 'linear-scan'
  | 'linear-scanner'
  | 'linear-scanning'
  | 'linear-scissor-1'
  | 'linear-scissor'
  | 'linear-scroll'
  | 'linear-search-favorite-1'
  | 'linear-search-favorite'
  | 'linear-search-normal-1'
  | 'linear-search-normal'
  | 'linear-search-status-1'
  | 'linear-search-status'
  | 'linear-search-zoom-in-1'
  | 'linear-search-zoom-in'
  | 'linear-search-zoom-out-1'
  | 'linear-search-zoom-out'
  | 'linear-security-card'
  | 'linear-security-safe'
  | 'linear-security-time'
  | 'linear-security-user'
  | 'linear-security'
  | 'linear-selector'
  | 'linear-send-2'
  | 'linear-send-sqaure-2'
  | 'linear-send-square'
  | 'linear-send'
  | 'linear-setting-2'
  | 'linear-setting-3'
  | 'linear-setting-4'
  | 'linear-setting-5'
  | 'linear-setting'
  | 'linear-settings'
  | 'linear-shapes-1'
  | 'linear-shapes-2'
  | 'linear-shapes'
  | 'linear-share'
  | 'linear-shield-cross'
  | 'linear-shield-search'
  | 'linear-shield-security'
  | 'linear-shield-slash'
  | 'linear-shield-tick'
  | 'linear-shield'
  | 'linear-ship'
  | 'linear-shop-add'
  | 'linear-shop-remove'
  | 'linear-shop'
  | 'linear-shopping-bag'
  | 'linear-shopping-cart'
  | 'linear-siacoin'
  | 'linear-sidebar-bottom'
  | 'linear-sidebar-left'
  | 'linear-sidebar-right'
  | 'linear-sidebar-top'
  | 'linear-signpost'
  | 'linear-simcard-1'
  | 'linear-simcard-2'
  | 'linear-simcard'
  | 'linear-size'
  | 'linear-slack'
  | 'linear-slash'
  | 'linear-slider-horizontal-1'
  | 'linear-slider-horizontal'
  | 'linear-slider-vertical-1'
  | 'linear-slider-vertical'
  | 'linear-slider'
  | 'linear-smallcaps'
  | 'linear-smart-car'
  | 'linear-smart-home'
  | 'linear-smileys'
  | 'linear-sms-edit'
  | 'linear-sms-notification'
  | 'linear-sms-search'
  | 'linear-sms-star'
  | 'linear-sms-tracking'
  | 'linear-sms'
  | 'linear-snapchat'
  | 'linear-solana'
  | 'linear-sort'
  | 'linear-sound'
  | 'linear-speaker'
  | 'linear-speedometer'
  | 'linear-spotify'
  | 'linear-stacks'
  | 'linear-star-1'
  | 'linear-star-slash'
  | 'linear-star'
  | 'linear-status-up'
  | 'linear-status'
  | 'linear-stellar'
  | 'linear-sticker'
  | 'linear-stickynote'
  | 'linear-story'
  | 'linear-strongbox-2'
  | 'linear-strongbox'
  | 'linear-sun-1'
  | 'linear-sun-fog'
  | 'linear-sun'
  | 'linear-tag-2'
  | 'linear-tag-cross'
  | 'linear-tag-right'
  | 'linear-tag-user'
  | 'linear-tag'
  | 'linear-task-square'
  | 'linear-task'
  | 'linear-teacher'
  | 'linear-tenx'
  | 'linear-tether'
  | 'linear-text-block'
  | 'linear-text-bold'
  | 'linear-text-italic'
  | 'linear-text-underline'
  | 'linear-text'
  | 'linear-textalign-center'
  | 'linear-textalign-justifycenter'
  | 'linear-textalign-justifyleft'
  | 'linear-textalign-justifyright'
  | 'linear-textalign-left'
  | 'linear-textalign-right'
  | 'linear-the-graph'
  | 'linear-theta'
  | 'linear-thorchain'
  | 'linear-tick-circle'
  | 'linear-tick-square'
  | 'linear-ticket-2'
  | 'linear-ticket-discount'
  | 'linear-ticket-expired'
  | 'linear-ticket-star'
  | 'linear-ticket'
  | 'linear-timer-1'
  | 'linear-timer-pause'
  | 'linear-timer-start'
  | 'linear-timer'
  | 'linear-toggle-off-circle'
  | 'linear-toggle-off'
  | 'linear-toggle-on-circle'
  | 'linear-toggle-on'
  | 'linear-trade'
  | 'linear-transaction-minus'
  | 'linear-translate'
  | 'linear-trash'
  | 'linear-tree'
  | 'linear-trello'
  | 'linear-trend-down'
  | 'linear-trend-up'
  | 'linear-triangle'
  | 'linear-trontron'
  | 'linear-truck-remove'
  | 'linear-truck-tick'
  | 'linear-truck-time'
  | 'linear-trush-square'
  | 'linear-twitch'
  | 'linear-ui8'
  | 'linear-undo'
  | 'linear-unlimited'
  | 'linear-unlock'
  | 'linear-usd-coin'
  | 'linear-user-add'
  | 'linear-user-cirlce-add'
  | 'linear-user-edit'
  | 'linear-user-minus'
  | 'linear-user-octagon'
  | 'linear-user-remove'
  | 'linear-user-search'
  | 'linear-user-square'
  | 'linear-user-tag'
  | 'linear-user-tick'
  | 'linear-user'
  | 'linear-velas'
  | 'linear-verify'
  | 'linear-vibe'
  | 'linear-vuesax'
  | 'linear-wallet-1'
  | 'linear-wallet-2'
  | 'linear-wallet-3'
  | 'linear-wallet-add-1'
  | 'linear-wallet-add'
  | 'linear-wallet-check'
  | 'linear-wallet-minus'
  | 'linear-wallet-money'
  | 'linear-wallet-remove'
  | 'linear-wallet-search'
  | 'linear-wallet'
  | 'linear-wanchain-1'
  | 'linear-wanchain'
  | 'linear-warning-2'
  | 'linear-watch-status'
  | 'linear-watch'
  | 'linear-weight'
  | 'linear-whatsapp'
  | 'linear-wifi-square'
  | 'linear-wifi'
  | 'linear-wind-2'
  | 'linear-wind'
  | 'linear-windows'
  | 'linear-wing'
  | 'linear-woman'
  | 'linear-xd'
  | 'linear-xiaomi'
  | 'linear-xrp'
  | 'linear-youtube'
  | 'linear-zel'
  | 'linear-zoom'
  ;

export type BoldIconName =
  'bold-24-support'
  | 'bold-3d-cube-scan'
  | 'bold-3d-rotate'
  | 'bold-3d-square'
  | 'bold-3dcube'
  | 'bold-3square'
  | 'bold-aave'
  | 'bold-activity'
  | 'bold-add-circle'
  | 'bold-add-square'
  | 'bold-add'
  | 'bold-additem'
  | 'bold-airdrop'
  | 'bold-airplane-square'
  | 'bold-airplane'
  | 'bold-airpod'
  | 'bold-airpods'
  | 'bold-alarm'
  | 'bold-align-bottom'
  | 'bold-align-horizontally'
  | 'bold-align-left'
  | 'bold-align-right'
  | 'bold-align-vertically'
  | 'bold-android'
  | 'bold-ankr'
  | 'bold-apple'
  | 'bold-aquarius'
  | 'bold-archive-1'
  | 'bold-archive-add'
  | 'bold-archive-book'
  | 'bold-archive-minus'
  | 'bold-archive-slash'
  | 'bold-archive-tick'
  | 'bold-archive'
  | 'bold-arrange-circle-2'
  | 'bold-arrange-circle'
  | 'bold-arrange-square-2'
  | 'bold-arrange-square'
  | 'bold-arrow-2'
  | 'bold-arrow-3'
  | 'bold-arrow-bottom'
  | 'bold-arrow-circle-down'
  | 'bold-arrow-circle-left'
  | 'bold-arrow-circle-right'
  | 'bold-arrow-circle-up'
  | 'bold-arrow-down-1'
  | 'bold-arrow-down-2'
  | 'bold-arrow-down'
  | 'bold-arrow-left-1'
  | 'bold-arrow-left-2'
  | 'bold-arrow-left-3'
  | 'bold-arrow-left'
  | 'bold-arrow-right-1'
  | 'bold-arrow-right-2'
  | 'bold-arrow-right-3'
  | 'bold-arrow-right'
  | 'bold-arrow-square-down'
  | 'bold-arrow-square-left'
  | 'bold-arrow-square-right'
  | 'bold-arrow-square-up'
  | 'bold-arrow-square'
  | 'bold-arrow-swap-horizontal'
  | 'bold-arrow-swap'
  | 'bold-arrow-up-1'
  | 'bold-arrow-up-2'
  | 'bold-arrow-up-3'
  | 'bold-arrow-up'
  | 'bold-arrow'
  | 'bold-attach-circle'
  | 'bold-attach-square'
  | 'bold-audio-square'
  | 'bold-augur'
  | 'bold-autobrightness'
  | 'bold-autonio'
  | 'bold-avalanche'
  | 'bold-award'
  | 'bold-back-square'
  | 'bold-backward-10-seconds'
  | 'bold-backward-15-seconds'
  | 'bold-backward-5-seconds'
  | 'bold-backward-item'
  | 'bold-backward'
  | 'bold-bag-2'
  | 'bold-bag-cross-1'
  | 'bold-bag-cross'
  | 'bold-bag-happy'
  | 'bold-bag-tick-2'
  | 'bold-bag-tick'
  | 'bold-bag-timer'
  | 'bold-bag'
  | 'bold-bank'
  | 'bold-barcode'
  | 'bold-battery-charging'
  | 'bold-battery-disable'
  | 'bold-battery-empty-1'
  | 'bold-battery-empty'
  | 'bold-battery-full'
  | 'bold-be'
  | 'bold-bezier'
  | 'bold-bill'
  | 'bold-binance-coin'
  | 'bold-binance-usd'
  | 'bold-bitcoin'
  | 'bold-bitcoin-card'
  | 'bold-bitcoin-convert'
  | 'bold-bitcoin-refresh'
  | 'bold-blend-2'
  | 'bold-blend'
  | 'bold-blogger'
  | 'bold-bluetooth-2'
  | 'bold-bluetooth-circle'
  | 'bold-bluetooth-rectangle'
  | 'bold-bluetooth'
  | 'bold-blur'
  | 'bold-book-1'
  | 'bold-book-saved'
  | 'bold-book-square'
  | 'bold-book'
  | 'bold-bookmark-2'
  | 'bold-bookmark'
  | 'bold-bootsrap'
  | 'bold-box-1'
  | 'bold-box-2'
  | 'bold-box-add'
  | 'bold-box-remove'
  | 'bold-box-search'
  | 'bold-box-tick'
  | 'bold-box-time'
  | 'bold-box'
  | 'bold-briefcase'
  | 'bold-brifecase-cross'
  | 'bold-brifecase-tick'
  | 'bold-brifecase-timer'
  | 'bold-broom'
  | 'bold-brush-1'
  | 'bold-brush-2'
  | 'bold-brush-3'
  | 'bold-brush-4'
  | 'bold-brush'
  | 'bold-bubble'
  | 'bold-bucket-circle'
  | 'bold-bucket-square'
  | 'bold-bucket'
  | 'bold-building-3'
  | 'bold-building-4'
  | 'bold-building'
  | 'bold-buildings-2'
  | 'bold-buildings'
  | 'bold-buliding'
  | 'bold-bus'
  | 'bold-buy-crypto'
  | 'bold-cake'
  | 'bold-calculator'
  | 'bold-calendar-1'
  | 'bold-calendar-2'
  | 'bold-calendar-add'
  | 'bold-calendar-circle'
  | 'bold-calendar-edit'
  | 'bold-calendar-remove'
  | 'bold-calendar-search'
  | 'bold-calendar-tick'
  | 'bold-calendar'
  | 'bold-call-add'
  | 'bold-call-calling'
  | 'bold-call-incoming'
  | 'bold-call-minus'
  | 'bold-call-outgoing'
  | 'bold-call-received'
  | 'bold-call-remove'
  | 'bold-call-slash'
  | 'bold-call'
  | 'bold-camera-slash'
  | 'bold-camera'
  | 'bold-candle-2'
  | 'bold-candle'
  | 'bold-car'
  | 'bold-card-add'
  | 'bold-card-coin'
  | 'bold-card-edit'
  | 'bold-card-pos'
  | 'bold-card-receive'
  | 'bold-card-remove-1'
  | 'bold-card-remove'
  | 'bold-card-send'
  | 'bold-card-slash'
  | 'bold-card-tick-1'
  | 'bold-card-tick'
  | 'bold-card'
  | 'bold-cardano'
  | 'bold-cards'
  | 'bold-category-2'
  | 'bold-category'
  | 'bold-cd'
  | 'bold-celo'
  | 'bold-celsius'
  | 'bold-chainlink'
  | 'bold-chart-1'
  | 'bold-chart-2'
  | 'bold-chart-21'
  | 'bold-chart-fail'
  | 'bold-chart-square'
  | 'bold-chart-success'
  | 'bold-chart'
  | 'bold-check'
  | 'bold-chrome'
  | 'bold-civic'
  | 'bold-clipboard-close'
  | 'bold-clipboard-export'
  | 'bold-clipboard-import'
  | 'bold-clipboard-text'
  | 'bold-clipboard-tick'
  | 'bold-clipboard'
  | 'bold-clock-1'
  | 'bold-clock'
  | 'bold-close-circle'
  | 'bold-close-square'
  | 'bold-cloud-add'
  | 'bold-cloud-change'
  | 'bold-cloud-connection'
  | 'bold-cloud-cross'
  | 'bold-cloud-drizzle'
  | 'bold-cloud-fog'
  | 'bold-cloud-lightning'
  | 'bold-cloud-minus'
  | 'bold-cloud-notif'
  | 'bold-cloud-plus'
  | 'bold-cloud-remove'
  | 'bold-cloud-snow'
  | 'bold-cloud-sunny'
  | 'bold-cloud'
  | 'bold-code-1'
  | 'bold-code-circle'
  | 'bold-code'
  | 'bold-coffee'
  | 'bold-coin-1'
  | 'bold-coin'
  | 'bold-color-swatch'
  | 'bold-colorfilter'
  | 'bold-colors-square'
  | 'bold-command-square'
  | 'bold-command'
  | 'bold-component'
  | 'bold-computing'
  | 'bold-convert-3d-cube'
  | 'bold-convert-card'
  | 'bold-convert'
  | 'bold-convertshape-2'
  | 'bold-convertshape'
  | 'bold-copy-success'
  | 'bold-copy'
  | 'bold-copyright'
  | 'bold-courthouse'
  | 'bold-cpu-charge'
  | 'bold-cpu-setting'
  | 'bold-cpu'
  | 'bold-creative-commons'
  | 'bold-crop'
  | 'bold-crown-1'
  | 'bold-crown'
  | 'bold-cup'
  | 'bold-dai'
  | 'bold-danger'
  | 'bold-dash'
  | 'bold-data-2'
  | 'bold-data'
  | 'bold-decred'
  | 'bold-dent'
  | 'bold-designtools'
  | 'bold-device-message'
  | 'bold-devices'
  | 'bold-diagram'
  | 'bold-diamonds'
  | 'bold-direct-down'
  | 'bold-direct-inbox'
  | 'bold-direct-left'
  | 'bold-direct-normal'
  | 'bold-direct-notification'
  | 'bold-direct-right'
  | 'bold-direct-send'
  | 'bold-direct-up'
  | 'bold-direct'
  | 'bold-directbox-default'
  | 'bold-directbox-notif'
  | 'bold-directbox-receive'
  | 'bold-directbox-send'
  | 'bold-discount-circle'
  | 'bold-discount-shape'
  | 'bold-discover'
  | 'bold-dislike'
  | 'bold-document-cloud'
  | 'bold-document-code-2'
  | 'bold-document-code'
  | 'bold-document-copy'
  | 'bold-document-download'
  | 'bold-document-favorite'
  | 'bold-document-filter'
  | 'bold-document-forward'
  | 'bold-document-like'
  | 'bold-document-normal'
  | 'bold-document-previous'
  | 'bold-document-sketch'
  | 'bold-document-text-1'
  | 'bold-document-text'
  | 'bold-document-upload'
  | 'bold-document'
  | 'bold-dollar-circle'
  | 'bold-dollar-square'
  | 'bold-dribbble'
  | 'bold-driver-2'
  | 'bold-driver-refresh'
  | 'bold-driver'
  | 'bold-driving'
  | 'bold-drop'
  | 'bold-dropbox'
  | 'bold-edit-2'
  | 'bold-edit'
  | 'bold-educare'
  | 'bold-electricity'
  | 'bold-element-2'
  | 'bold-element-3'
  | 'bold-element-4'
  | 'bold-element-equal'
  | 'bold-element-plus'
  | 'bold-emercoin'
  | 'bold-emoji-happy'
  | 'bold-emoji-normal'
  | 'bold-emoji-sad'
  | 'bold-empty-wallet-add'
  | 'bold-empty-wallet-change'
  | 'bold-empty-wallet-remove'
  | 'bold-empty-wallet-tick'
  | 'bold-empty-wallet-time'
  | 'bold-empty-wallet'
  | 'bold-enjin-coin'
  | 'bold-eos'
  | 'bold-eraser'
  | 'bold-ethereum'
  | 'bold-ethereum-classic'
  | 'bold-export-1'
  | 'bold-export-2'
  | 'bold-export-3'
  | 'bold-export'
  | 'bold-external-drive'
  | 'bold-eye-slash'
  | 'bold-eye'
  | 'bold-facebook'
  | 'bold-fatrows'
  | 'bold-favorite-chart'
  | 'bold-figma-1'
  | 'bold-figma'
  | 'bold-filter-add'
  | 'bold-filter-edit'
  | 'bold-filter-remove'
  | 'bold-filter-search'
  | 'bold-filter-square'
  | 'bold-filter-tick'
  | 'bold-filter'
  | 'bold-finger-cricle'
  | 'bold-finger-scan'
  | 'bold-firstline'
  | 'bold-flag-2'
  | 'bold-flag'
  | 'bold-flash-circle-1'
  | 'bold-flash-circle'
  | 'bold-flash-slash'
  | 'bold-flash'
  | 'bold-folder-2'
  | 'bold-folder-add'
  | 'bold-folder-cloud'
  | 'bold-folder-connection'
  | 'bold-folder-cross'
  | 'bold-folder-favorite'
  | 'bold-folder-minus'
  | 'bold-folder-open'
  | 'bold-folder'
  | 'bold-forbidden-2'
  | 'bold-forbidden'
  | 'bold-format-circle'
  | 'bold-format-square'
  | 'bold-forward-10-seconds'
  | 'bold-forward-15-seconds'
  | 'bold-forward-5-seconds'
  | 'bold-forward-item'
  | 'bold-forward-square'
  | 'bold-forward'
  | 'bold-frame-1'
  | 'bold-frame-2'
  | 'bold-frame'
  | 'bold-framer'
  | 'bold-ftx-token'
  | 'bold-gallery-add'
  | 'bold-gallery-edit'
  | 'bold-gallery-export'
  | 'bold-gallery-favorite'
  | 'bold-gallery-import'
  | 'bold-gallery-remove'
  | 'bold-gallery-slash'
  | 'bold-gallery-tick'
  | 'bold-gallery'
  | 'bold-game'
  | 'bold-gameboy'
  | 'bold-gas-station'
  | 'bold-gemini-2'
  | 'bold-gemini'
  | 'bold-ghost'
  | 'bold-gift'
  | 'bold-glass-1'
  | 'bold-glass'
  | 'bold-global-edit'
  | 'bold-global-refresh'
  | 'bold-global-search'
  | 'bold-global'
  | 'bold-google-1'
  | 'bold-google-play'
  | 'bold-google'
  | 'bold-gps-slash'
  | 'bold-gps'
  | 'bold-grammerly'
  | 'bold-graph'
  | 'bold-grid-1'
  | 'bold-grid-2'
  | 'bold-grid-3'
  | 'bold-grid-4'
  | 'bold-grid-5'
  | 'bold-grid-6'
  | 'bold-grid-7'
  | 'bold-grid-8'
  | 'bold-grid-9'
  | 'bold-grid-edit'
  | 'bold-grid-eraser'
  | 'bold-grid-lock'
  | 'bold-happyemoji'
  | 'bold-harmony'
  | 'bold-hashtag-down'
  | 'bold-hashtag-up'
  | 'bold-hashtag'
  | 'bold-headphone'
  | 'bold-headphones'
  | 'bold-health'
  | 'bold-heart-add'
  | 'bold-heart-circle'
  | 'bold-heart-edit'
  | 'bold-heart-remove'
  | 'bold-heart-search'
  | 'bold-heart-slash'
  | 'bold-heart-tick'
  | 'bold-heart'
  | 'bold-hedera-hashgraph'
  | 'bold-hex'
  | 'bold-hierarchy-2'
  | 'bold-hierarchy-3'
  | 'bold-hierarchy-square-2'
  | 'bold-hierarchy-square-3'
  | 'bold-hierarchy-square'
  | 'bold-hierarchy'
  | 'bold-home-1'
  | 'bold-home-2'
  | 'bold-home-hashtag'
  | 'bold-home-trend-down'
  | 'bold-home-trend-up'
  | 'bold-home-wifi'
  | 'bold-home'
  | 'bold-hospital'
  | 'bold-house-2'
  | 'bold-house'
  | 'bold-html-3'
  | 'bold-html-5'
  | 'bold-huobi-token'
  | 'bold-icon'
  | 'bold-icon-1'
  | 'bold-illustrator'
  | 'bold-image'
  | 'bold-import-1'
  | 'bold-import-2'
  | 'bold-import-3'
  | 'bold-import'
  | 'bold-info-circle'
  | 'bold-information'
  | 'bold-instagram'
  | 'bold-iost'
  | 'bold-java-script'
  | 'bold-js'
  | 'bold-judge'
  | 'bold-kanban'
  | 'bold-key-square'
  | 'bold-key'
  | 'bold-keyboard-open'
  | 'bold-keyboard'
  | 'bold-kyber-network'
  | 'bold-lamp-1'
  | 'bold-lamp-charge'
  | 'bold-lamp-on'
  | 'bold-lamp-slash'
  | 'bold-lamp'
  | 'bold-language-circle'
  | 'bold-language-square'
  | 'bold-layer'
  | 'bold-level'
  | 'bold-lifebuoy'
  | 'bold-like-1'
  | 'bold-like-dislike'
  | 'bold-like-shapes'
  | 'bold-like-tag'
  | 'bold-like'
  | 'bold-link-1'
  | 'bold-link-2'
  | 'bold-link-21'
  | 'bold-link-circle'
  | 'bold-link-square'
  | 'bold-link'
  | 'bold-litecoin'
  | 'bold-location-add'
  | 'bold-location-cross'
  | 'bold-location-minus'
  | 'bold-location-slash'
  | 'bold-location-tick'
  | 'bold-location'
  | 'bold-lock-1'
  | 'bold-lock-circle'
  | 'bold-lock-slash'
  | 'bold-lock'
  | 'bold-login-1'
  | 'bold-login'
  | 'bold-logout-1'
  | 'bold-logout'
  | 'bold-lovely'
  | 'bold-magic-star'
  | 'bold-magicpen'
  | 'bold-main-component'
  | 'bold-maker'
  | 'bold-man'
  | 'bold-map-1'
  | 'bold-map'
  | 'bold-mask-1'
  | 'bold-mask-2'
  | 'bold-mask'
  | 'bold-math'
  | 'bold-maximize-1'
  | 'bold-maximize-2'
  | 'bold-maximize-3'
  | 'bold-maximize-4'
  | 'bold-maximize-circle'
  | 'bold-maximize'
  | 'bold-medal-star'
  | 'bold-medal'
  | 'bold-menu-1'
  | 'bold-menu-board'
  | 'bold-menu'
  | 'bold-message-2'
  | 'bold-message-add-1'
  | 'bold-message-add'
  | 'bold-message-circle'
  | 'bold-message-edit'
  | 'bold-message-favorite'
  | 'bold-message-minus'
  | 'bold-message-notif'
  | 'bold-message-programming'
  | 'bold-message-question'
  | 'bold-message-remove'
  | 'bold-message-search'
  | 'bold-message-square'
  | 'bold-message-text-1'
  | 'bold-message-text'
  | 'bold-message-tick'
  | 'bold-message-time'
  | 'bold-message'
  | 'bold-messages-1'
  | 'bold-messages-2'
  | 'bold-messages-3'
  | 'bold-messages'
  | 'bold-messenger'
  | 'bold-microphone-2'
  | 'bold-microphone-slash-1'
  | 'bold-microphone-slash'
  | 'bold-microphone'
  | 'bold-microscope'
  | 'bold-milk'
  | 'bold-mini-music-sqaure'
  | 'bold-minus-cirlce'
  | 'bold-minus-square'
  | 'bold-minus'
  | 'bold-mirror'
  | 'bold-mirroring-screen'
  | 'bold-mobile-programming'
  | 'bold-mobile'
  | 'bold-monero'
  | 'bold-money-2'
  | 'bold-money-3'
  | 'bold-money-4'
  | 'bold-money-add'
  | 'bold-money-change'
  | 'bold-money-forbidden'
  | 'bold-money-recive'
  | 'bold-money-remove'
  | 'bold-money-send'
  | 'bold-money-tick'
  | 'bold-money-time'
  | 'bold-money'
  | 'bold-moneys'
  | 'bold-monitor-mobbile'
  | 'bold-monitor-recorder'
  | 'bold-monitor'
  | 'bold-moon'
  | 'bold-more-2'
  | 'bold-more-circle'
  | 'bold-more-square'
  | 'bold-more'
  | 'bold-mouse-1'
  | 'bold-mouse-circle'
  | 'bold-mouse-square'
  | 'bold-mouse'
  | 'bold-music-circle'
  | 'bold-music-dashboard'
  | 'bold-music-filter'
  | 'bold-music-library-2'
  | 'bold-music-play'
  | 'bold-music-playlist'
  | 'bold-music-square-add'
  | 'bold-music-square-remove'
  | 'bold-music-square-search'
  | 'bold-music-square'
  | 'bold-music'
  | 'bold-musicnote'
  | 'bold-nebulas'
  | 'bold-nem'
  | 'bold-nexo'
  | 'bold-next'
  | 'bold-note-1'
  | 'bold-note-2'
  | 'bold-note-add'
  | 'bold-note-favorite'
  | 'bold-note-remove'
  | 'bold-note-square'
  | 'bold-note-text'
  | 'bold-note'
  | 'bold-notification-1'
  | 'bold-notification-bing'
  | 'bold-notification-favorite'
  | 'bold-notification-status'
  | 'bold-notification'
  | 'bold-ocean-protocol'
  | 'bold-okb'
  | 'bold-omega-circle'
  | 'bold-omega-square'
  | 'bold-ontology'
  | 'bold-paintbucket'
  | 'bold-paperclip-2'
  | 'bold-paperclip'
  | 'bold-password-check'
  | 'bold-path-2'
  | 'bold-path-square'
  | 'bold-path'
  | 'bold-pause-circle'
  | 'bold-pause'
  | 'bold-paypal'
  | 'bold-pen-add'
  | 'bold-pen-close'
  | 'bold-pen-remove'
  | 'bold-pen-tool-2'
  | 'bold-pen-tool'
  | 'bold-people'
  | 'bold-percentage-circle'
  | 'bold-percentage-square'
  | 'bold-personalcard'
  | 'bold-pet'
  | 'bold-pharagraphspacing'
  | 'bold-photoshop'
  | 'bold-picture-frame'
  | 'bold-play-add'
  | 'bold-play-circle'
  | 'bold-play-cricle'
  | 'bold-play-remove'
  | 'bold-play'
  | 'bold-polkadot'
  | 'bold-polygon'
  | 'bold-polyswarm'
  | 'bold-presention-chart'
  | 'bold-previous'
  | 'bold-printer-slash'
  | 'bold-printer'
  | 'bold-profile-2user'
  | 'bold-profile-add'
  | 'bold-profile-circle'
  | 'bold-profile-delete'
  | 'bold-profile-remove'
  | 'bold-profile-tick'
  | 'bold-programming-arrow'
  | 'bold-programming-arrows'
  | 'bold-python'
  | 'bold-quant'
  | 'bold-quote-down-circle'
  | 'bold-quote-down-square'
  | 'bold-quote-down'
  | 'bold-quote-up-circle'
  | 'bold-quote-up-square'
  | 'bold-quote-up'
  | 'bold-radar-1'
  | 'bold-radar-2'
  | 'bold-radar'
  | 'bold-radio'
  | 'bold-ram-2'
  | 'bold-ram'
  | 'bold-ranking-1'
  | 'bold-ranking'
  | 'bold-receipt-1'
  | 'bold-receipt-2-1'
  | 'bold-receipt-2'
  | 'bold-receipt-add'
  | 'bold-receipt-discount'
  | 'bold-receipt-disscount'
  | 'bold-receipt-edit'
  | 'bold-receipt-item'
  | 'bold-receipt-minus'
  | 'bold-receipt-search'
  | 'bold-receipt-square'
  | 'bold-receipt-text'
  | 'bold-receipt'
  | 'bold-receive-square-2'
  | 'bold-receive-square'
  | 'bold-received'
  | 'bold-record-circle'
  | 'bold-record'
  | 'bold-recovery-convert'
  | 'bold-redo'
  | 'bold-refresh-2'
  | 'bold-refresh-circle'
  | 'bold-refresh-left-square'
  | 'bold-refresh-right-square'
  | 'bold-refresh-square-2'
  | 'bold-refresh'
  | 'bold-repeat-circle'
  | 'bold-repeat'
  | 'bold-repeate-music'
  | 'bold-repeate-one'
  | 'bold-reserve'
  | 'bold-rotate-left'
  | 'bold-rotate-right'
  | 'bold-route-square'
  | 'bold-routing-2'
  | 'bold-routing'
  | 'bold-row-horizontal'
  | 'bold-row-vertical'
  | 'bold-rulerpen'
  | 'bold-ruler'
  | 'bold-safe-home'
  | 'bold-sagittarius'
  | 'bold-save-2'
  | 'bold-save-add'
  | 'bold-save-minus'
  | 'bold-save-remove'
  | 'bold-scan-barcode'
  | 'bold-scan'
  | 'bold-scanner'
  | 'bold-scanning'
  | 'bold-scissor'
  | 'bold-screenmirroring'
  | 'bold-scroll'
  | 'bold-search-favorite-1'
  | 'bold-search-favorite'
  | 'bold-search-normal-1'
  | 'bold-search-normal'
  | 'bold-search-status-1'
  | 'bold-search-status'
  | 'bold-search-zoom-in-1'
  | 'bold-search-zoom-in'
  | 'bold-search-zoom-out-1'
  | 'bold-search-zoom-out'
  | 'bold-security-card'
  | 'bold-security-safe'
  | 'bold-security-time'
  | 'bold-security-user'
  | 'bold-security'
  | 'bold-send-2'
  | 'bold-send-sqaure-2'
  | 'bold-send-square'
  | 'bold-send'
  | 'bold-setting-2'
  | 'bold-setting-3'
  | 'bold-setting-4'
  | 'bold-setting-5'
  | 'bold-setting'
  | 'bold-settings'
  | 'bold-shapes-1'
  | 'bold-shapes'
  | 'bold-share'
  | 'bold-shield-cross'
  | 'bold-shield-search'
  | 'bold-shield-security'
  | 'bold-shield-slash'
  | 'bold-shield-tick'
  | 'bold-ship'
  | 'bold-shop-add'
  | 'bold-shop-remove'
  | 'bold-shop'
  | 'bold-shopping-bag'
  | 'bold-shopping-cart'
  | 'bold-shuffle'
  | 'bold-siacoin'
  | 'bold-sidebar-bottom'
  | 'bold-sidebar-left'
  | 'bold-sidebar-right'
  | 'bold-sidebar-top'
  | 'bold-signpost'
  | 'bold-simcard-1'
  | 'bold-simcard-2'
  | 'bold-simcard'
  | 'bold-size'
  | 'bold-slack'
  | 'bold-slash'
  | 'bold-slider-horizontal-1'
  | 'bold-slider-horizontal'
  | 'bold-slider-vertical-1'
  | 'bold-slider-vertical'
  | 'bold-slider'
  | 'bold-smallcaps'
  | 'bold-smart-car'
  | 'bold-smart-home'
  | 'bold-smileys'
  | 'bold-sms-edit'
  | 'bold-sms-notification'
  | 'bold-sms-search'
  | 'bold-sms-star'
  | 'bold-sms-tracking'
  | 'bold-sms'
  | 'bold-snapchat'
  | 'bold-solana'
  | 'bold-sort'
  | 'bold-sound'
  | 'bold-speaker'
  | 'bold-speedometer'
  | 'bold-spotify'
  | 'bold-stacks'
  | 'bold-star-1'
  | 'bold-star-slash'
  | 'bold-star'
  | 'bold-status-up'
  | 'bold-status'
  | 'bold-stellar'
  | 'bold-sticker'
  | 'bold-stickynote'
  | 'bold-stop-circle'
  | 'bold-stop'
  | 'bold-story'
  | 'bold-strongbox-2'
  | 'bold-strongbox'
  | 'bold-subtitle'
  | 'bold-sun-1'
  | 'bold-sun-fog'
  | 'bold-sun'
  | 'bold-tag-2'
  | 'bold-tag-cross'
  | 'bold-tag-right'
  | 'bold-tag-user'
  | 'bold-tag'
  | 'bold-task-square'
  | 'bold-task'
  | 'bold-teacher'
  | 'bold-tenx'
  | 'bold-tether'
  | 'bold-text-block'
  | 'bold-text-bold'
  | 'bold-text-italic'
  | 'bold-text-underline'
  | 'bold-text'
  | 'bold-textalign-center'
  | 'bold-textalign-justifycenter'
  | 'bold-textalign-justifyleft'
  | 'bold-textalign-justifyright'
  | 'bold-textalign-left'
  | 'bold-textalign-right'
  | 'bold-the-graph'
  | 'bold-theta'
  | 'bold-thorchain'
  | 'bold-tick-circle'
  | 'bold-tick-square'
  | 'bold-ticket-2'
  | 'bold-ticket-discount'
  | 'bold-ticket-expired'
  | 'bold-ticket-star'
  | 'bold-ticket'
  | 'bold-timer-1'
  | 'bold-timer-pause'
  | 'bold-timer-start'
  | 'bold-timer'
  | 'bold-toggle-off-circle'
  | 'bold-toggle-off'
  | 'bold-toggle-on-circle'
  | 'bold-toggle-on'
  | 'bold-trade'
  | 'bold-transaction-minus'
  | 'bold-translate'
  | 'bold-trash'
  | 'bold-tree'
  | 'bold-trello'
  | 'bold-trend-down'
  | 'bold-trend-up'
  | 'bold-triangle'
  | 'bold-trontron'
  | 'bold-truck-fast'
  | 'bold-truck-remove'
  | 'bold-truck-tick'
  | 'bold-truck-time'
  | 'bold-truck'
  | 'bold-trush-square'
  | 'bold-twitch'
  | 'bold-ui8'
  | 'bold-undo'
  | 'bold-unlimited'
  | 'bold-unlock'
  | 'bold-usd-coin'
  | 'bold-user-add'
  | 'bold-user-cirlce-add'
  | 'bold-user-edit'
  | 'bold-user-minus'
  | 'bold-user-octagon'
  | 'bold-user-remove'
  | 'bold-user-search'
  | 'bold-user-square'
  | 'bold-user-tag'
  | 'bold-user-tick'
  | 'bold-user'
  | 'bold-velas'
  | 'bold-verify'
  | 'bold-vibe'
  | 'bold-video-add'
  | 'bold-video-circle'
  | 'bold-video-horizontal'
  | 'bold-video-octagon'
  | 'bold-video-play'
  | 'bold-video-remove'
  | 'bold-video-slash'
  | 'bold-video-square'
  | 'bold-video-tick'
  | 'bold-video-time'
  | 'bold-video-vertical'
  | 'bold-video'
  | 'bold-voice-cricle'
  | 'bold-voice-square'
  | 'bold-volume-cross'
  | 'bold-volume-high'
  | 'bold-volume-low-1'
  | 'bold-volume-low'
  | 'bold-volume-mute'
  | 'bold-volume-slash'
  | 'bold-volume-up'
  | 'bold-vuesax'
  | 'bold-wallet-1'
  | 'bold-wallet-2'
  | 'bold-wallet-3'
  | 'bold-wallet-add-1'
  | 'bold-wallet-add'
  | 'bold-wallet-check'
  | 'bold-wallet-minus'
  | 'bold-wallet-money'
  | 'bold-wallet-remove'
  | 'bold-wallet-search'
  | 'bold-wallet'
  | 'bold-wanchain-1'
  | 'bold-wanchain'
  | 'bold-warning-2'
  | 'bold-watch-status'
  | 'bold-watch'
  | 'bold-weight-1'
  | 'bold-weight'
  | 'bold-whatsapp'
  | 'bold-wifi-square'
  | 'bold-wifi'
  | 'bold-wind-2'
  | 'bold-wind'
  | 'bold-windows'
  | 'bold-wing'
  | 'bold-woman'
  | 'bold-xd'
  | 'bold-xiaomi'
  | 'bold-xrp'
  | 'bold-youtube'
  | 'bold-zel'
  | 'bold-zoom'
  ;

/** Union of all available icon IDs in the AXIO sprite sheet */
export type IconName = LinearIconName | BoldIconName;

export const LINEAR_ICON_NAMES: LinearIconName[] = [
  'linear-24-support',
  'linear-3d-cube-scan',
  'linear-3d-rotate',
  'linear-3d-square',
  'linear-3dcube',
  'linear-3square',
  'linear-aave',
  'linear-activity',
  'linear-add-circle',
  'linear-add-square',
  'linear-add',
  'linear-additem',
  'linear-airdrop',
  'linear-airplane-square',
  'linear-airplane',
  'linear-airpod',
  'linear-airpods',
  'linear-alarm',
  'linear-align-bottom',
  'linear-align-horizontally',
  'linear-align-left',
  'linear-align-right',
  'linear-align-vertically',
  'linear-android',
  'linear-ankr',
  'linear-apple',
  'linear-aquarius',
  'linear-archive-add',
  'linear-archive-book',
  'linear-archive-minus',
  'linear-archive-slash',
  'linear-archive-tick',
  'linear-archive',
  'linear-arrange-circle-2',
  'linear-arrange-circle',
  'linear-arrange-square-2',
  'linear-arrange-square',
  'linear-arrow-2',
  'linear-arrow-3',
  'linear-arrow-bottom',
  'linear-arrow-circle-down',
  'linear-arrow-circle-left',
  'linear-arrow-circle-right',
  'linear-arrow-down-1',
  'linear-arrow-down-2',
  'linear-arrow-down',
  'linear-arrow-left-1',
  'linear-arrow-left-2',
  'linear-arrow-left-3',
  'linear-arrow-left',
  'linear-arrow-right-1',
  'linear-arrow-right-2',
  'linear-arrow-right-3',
  'linear-arrow-right',
  'linear-arrow-square-down',
  'linear-arrow-square-left',
  'linear-arrow-square-right',
  'linear-arrow-square-up',
  'linear-arrow-square',
  'linear-arrow-swap-horizontal',
  'linear-arrow-up-1',
  'linear-arrow-up-2',
  'linear-arrow-up-3',
  'linear-arrow-up',
  'linear-arrow',
  'linear-attach-circle',
  'linear-attach-square',
  'linear-augur',
  'linear-autobrightness',
  'linear-autonio',
  'linear-avalanche',
  'linear-award',
  'linear-back-square',
  'linear-backward-item-1',
  'linear-backward-item',
  'linear-bag-2',
  'linear-bag-cross-1',
  'linear-bag-cross',
  'linear-bag-happy',
  'linear-bag-tick-2',
  'linear-bag-tick',
  'linear-bag-timer',
  'linear-bag',
  'linear-bank',
  'linear-barcode',
  'linear-battery-charging',
  'linear-battery-disable',
  'linear-battery-empty-1',
  'linear-battery-empty',
  'linear-battery-full',
  'linear-be',
  'linear-bezier-1',
  'linear-bezier',
  'linear-bill',
  'linear-binance-coin',
  'linear-binance-usd',
  'linear-bitcoin',
  'linear-bitcoin-card',
  'linear-bitcoin-convert',
  'linear-bitcoin-refresh',
  'linear-blend-2',
  'linear-blend',
  'linear-blogger',
  'linear-bluetooth-2',
  'linear-bluetooth-circle',
  'linear-bluetooth-rectangle',
  'linear-bluetooth',
  'linear-blur-1',
  'linear-blur',
  'linear-book-1',
  'linear-book-saved',
  'linear-book-square',
  'linear-book',
  'linear-bookmark-2',
  'linear-bookmark',
  'linear-bootsrap',
  'linear-box-1',
  'linear-box-2',
  'linear-box-add',
  'linear-box-remove',
  'linear-box-search',
  'linear-box-tick',
  'linear-box-time',
  'linear-box',
  'linear-briefcase',
  'linear-brifecase-cross',
  'linear-brifecase-tick',
  'linear-brifecase-timer',
  'linear-broom',
  'linear-brush-1',
  'linear-brush-2',
  'linear-brush-3',
  'linear-brush',
  'linear-bubble',
  'linear-bucket-circle-1',
  'linear-bucket-circle',
  'linear-bucket-square-1',
  'linear-bucket-square',
  'linear-building-3',
  'linear-building-4',
  'linear-building',
  'linear-buildings-2',
  'linear-buildings',
  'linear-buliding',
  'linear-bus',
  'linear-buy-crypto',
  'linear-cake',
  'linear-calculator',
  'linear-calendar-1',
  'linear-calendar-2',
  'linear-calendar-add',
  'linear-calendar-circle',
  'linear-calendar-edit',
  'linear-calendar-remove',
  'linear-calendar-search',
  'linear-calendar-tick',
  'linear-calendar',
  'linear-call-add',
  'linear-call-calling',
  'linear-call-incoming',
  'linear-call-minus',
  'linear-call-outgoing',
  'linear-call-received',
  'linear-call-remove',
  'linear-call-slash',
  'linear-call',
  'linear-candle-2',
  'linear-candle',
  'linear-car',
  'linear-card-add',
  'linear-card-coin',
  'linear-card-edit',
  'linear-card-pos',
  'linear-card-receive',
  'linear-card-remove-1',
  'linear-card-remove',
  'linear-card-send',
  'linear-card-slash',
  'linear-card-tick-1',
  'linear-card-tick',
  'linear-card',
  'linear-cardano',
  'linear-cards',
  'linear-category-2',
  'linear-category',
  'linear-cd',
  'linear-celo',
  'linear-celsius',
  'linear-chainlink',
  'linear-chart-1',
  'linear-chart-2',
  'linear-chart-21',
  'linear-chart-square',
  'linear-chart-success',
  'linear-chart',
  'linear-check',
  'linear-chrome',
  'linear-civic',
  'linear-clipboard-close',
  'linear-clipboard-export',
  'linear-clipboard-import',
  'linear-clipboard-text',
  'linear-clipboard-tick',
  'linear-clipboard',
  'linear-clock-1',
  'linear-clock',
  'linear-close-circle',
  'linear-close-square',
  'linear-cloud-add',
  'linear-cloud-change',
  'linear-cloud-connection',
  'linear-cloud-cross',
  'linear-cloud-drizzle',
  'linear-cloud-fog',
  'linear-cloud-lightning',
  'linear-cloud-minus',
  'linear-cloud-notif',
  'linear-cloud-plus',
  'linear-cloud-remove',
  'linear-cloud-snow',
  'linear-cloud-sunny',
  'linear-cloud',
  'linear-code-1',
  'linear-code-circle',
  'linear-code',
  'linear-coffee',
  'linear-coin-1',
  'linear-coin',
  'linear-color-swatch',
  'linear-colorfilter',
  'linear-colors-square-1',
  'linear-colors-square',
  'linear-command-square',
  'linear-command',
  'linear-component-1',
  'linear-component',
  'linear-computing',
  'linear-convert-3d-cube',
  'linear-convert',
  'linear-convertshape-2',
  'linear-convertshape',
  'linear-copy-success',
  'linear-copy',
  'linear-copyright',
  'linear-courthouse',
  'linear-cpu-charge',
  'linear-cpu-setting',
  'linear-cpu',
  'linear-creative-commons',
  'linear-crop',
  'linear-crown-1',
  'linear-crown',
  'linear-cup',
  'linear-dai',
  'linear-danger',
  'linear-dash',
  'linear-data-2',
  'linear-data',
  'linear-decred',
  'linear-dent',
  'linear-designtools',
  'linear-device-message',
  'linear-devices',
  'linear-diagram',
  'linear-diamonds',
  'linear-direct-down',
  'linear-direct-inbox',
  'linear-direct-left',
  'linear-direct-normal',
  'linear-direct-notification',
  'linear-direct-right',
  'linear-direct-send',
  'linear-direct-up',
  'linear-direct',
  'linear-directbox-default',
  'linear-directbox-notif',
  'linear-directbox-receive',
  'linear-directbox-send',
  'linear-discount-circle',
  'linear-discount-shape',
  'linear-discover-1',
  'linear-discover',
  'linear-dislike',
  'linear-document-cloud',
  'linear-document-code-2',
  'linear-document-code',
  'linear-document-copy',
  'linear-document-download',
  'linear-document-favorite',
  'linear-document-filter',
  'linear-document-forward',
  'linear-document-like',
  'linear-document-previous',
  'linear-document-sketch',
  'linear-document-text-1',
  'linear-document-text',
  'linear-document-upload',
  'linear-document',
  'linear-dollar-circle',
  'linear-dollar-square',
  'linear-dribbble',
  'linear-driver-2',
  'linear-driver-refresh',
  'linear-driver',
  'linear-driving',
  'linear-drop',
  'linear-dropbox',
  'linear-edit-2',
  'linear-edit',
  'linear-educare',
  'linear-electricity',
  'linear-element-1',
  'linear-element-2',
  'linear-element-3',
  'linear-element-4',
  'linear-element-equal',
  'linear-element-plus',
  'linear-emercoin',
  'linear-emoji-happy',
  'linear-emoji-normal-1',
  'linear-emoji-normal',
  'linear-emoji-sad',
  'linear-emoji-super',
  'linear-empty-wallet-add',
  'linear-empty-wallet-change',
  'linear-empty-wallet-remove',
  'linear-empty-wallet-tick',
  'linear-empty-wallet-time',
  'linear-empty-wallet',
  'linear-enjin-coin',
  'linear-eos',
  'linear-eraser-1',
  'linear-eraser',
  'linear-ethereum',
  'linear-ethereum-classic',
  'linear-export-1',
  'linear-export-2',
  'linear-export-3',
  'linear-export',
  'linear-external-drive',
  'linear-eye-slash',
  'linear-eye',
  'linear-facebook',
  'linear-fatrows',
  'linear-favorite-chart',
  'linear-figma-1',
  'linear-figma',
  'linear-filter-add',
  'linear-filter-edit',
  'linear-filter-remove',
  'linear-filter-search',
  'linear-filter-square',
  'linear-filter-tick',
  'linear-filter',
  'linear-finger-cricle',
  'linear-finger-scan',
  'linear-firstline',
  'linear-flag-2',
  'linear-flag',
  'linear-flash-circle-1',
  'linear-flash-circle-2',
  'linear-flash-circle',
  'linear-flash-slash',
  'linear-flash',
  'linear-folder-2',
  'linear-folder-add',
  'linear-folder-cloud',
  'linear-folder-connection',
  'linear-folder-cross',
  'linear-folder-favorite',
  'linear-folder-minus',
  'linear-folder-open',
  'linear-folder',
  'linear-format-circle',
  'linear-format-square',
  'linear-forward-item-1',
  'linear-forward-item',
  'linear-forward-square',
  'linear-frame-1',
  'linear-frame-2',
  'linear-frame-3',
  'linear-frame',
  'linear-framer',
  'linear-ftx-token',
  'linear-game',
  'linear-gameboy',
  'linear-gas-station',
  'linear-gemini-2',
  'linear-gemini',
  'linear-ghost',
  'linear-gift',
  'linear-glass-1',
  'linear-glass',
  'linear-global-edit',
  'linear-global-refresh',
  'linear-global-search',
  'linear-global',
  'linear-google-1',
  'linear-google-play',
  'linear-google',
  'linear-gps-slash',
  'linear-gps',
  'linear-grammerly',
  'linear-graph',
  'linear-grid-1',
  'linear-grid-2',
  'linear-grid-3',
  'linear-grid-4',
  'linear-grid-5',
  'linear-grid-6',
  'linear-grid-7',
  'linear-grid-8',
  'linear-grid-9',
  'linear-grid-edit',
  'linear-grid-eraser',
  'linear-grid-lock',
  'linear-group-1',
  'linear-group-2',
  'linear-group-3',
  'linear-group-4',
  'linear-group-5',
  'linear-group-6',
  'linear-group-7',
  'linear-group-8',
  'linear-group',
  'linear-happyemoji',
  'linear-harmony',
  'linear-hashtag-down',
  'linear-hashtag-up',
  'linear-hashtag',
  'linear-headphone',
  'linear-headphones',
  'linear-health',
  'linear-heart-add',
  'linear-heart-circle',
  'linear-heart-edit',
  'linear-heart-remove',
  'linear-heart-search',
  'linear-heart-slash',
  'linear-heart-tick',
  'linear-heart',
  'linear-hedera-hashgraph',
  'linear-hex',
  'linear-hierarchy-2',
  'linear-hierarchy-3',
  'linear-hierarchy-square-2',
  'linear-hierarchy-square-3',
  'linear-hierarchy-square',
  'linear-hierarchy',
  'linear-home-2',
  'linear-home-hashtag',
  'linear-home-trend-down',
  'linear-home-trend-up',
  'linear-home-wifi',
  'linear-home',
  'linear-hospital',
  'linear-house-2',
  'linear-house',
  'linear-html-3',
  'linear-html-5',
  'linear-huobi-token',
  'linear-icon',
  'linear-illustrator',
  'linear-import-1',
  'linear-import-2',
  'linear-import',
  'linear-info-circle',
  'linear-information',
  'linear-instagram',
  'linear-iost',
  'linear-java-script',
  'linear-js',
  'linear-judge',
  'linear-kanban',
  'linear-key-square',
  'linear-key',
  'linear-keyboard-open',
  'linear-keyboard',
  'linear-kyber-network',
  'linear-lamp-charge',
  'linear-lamp-on',
  'linear-lamp-slash',
  'linear-lamp',
  'linear-language-circle',
  'linear-language-square',
  'linear-layer',
  'linear-level',
  'linear-lifebuoy',
  'linear-like-1',
  'linear-like-dislike',
  'linear-like-shapes',
  'linear-like-tag',
  'linear-like',
  'linear-link-1',
  'linear-link-2',
  'linear-link-21',
  'linear-link-circle',
  'linear-link-square',
  'linear-link',
  'linear-litecoin',
  'linear-location-add',
  'linear-location-cross',
  'linear-location-minus',
  'linear-location-slash',
  'linear-location-tick',
  'linear-location',
  'linear-lock-1',
  'linear-lock-circle',
  'linear-lock-slash',
  'linear-lock',
  'linear-login-1',
  'linear-login',
  'linear-logout-1',
  'linear-logout',
  'linear-lovely',
  'linear-magic-star',
  'linear-magicpen',
  'linear-main-component-1',
  'linear-main-component',
  'linear-maker',
  'linear-man',
  'linear-map-1',
  'linear-map',
  'linear-mask-1',
  'linear-mask-2',
  'linear-mask-3',
  'linear-mask',
  'linear-math',
  'linear-maximize-1',
  'linear-maximize-2',
  'linear-maximize-3',
  'linear-maximize-4',
  'linear-maximize',
  'linear-medal-star',
  'linear-medal',
  'linear-menu-board',
  'linear-menu',
  'linear-message-2',
  'linear-message-add-1',
  'linear-message-add',
  'linear-message-circle',
  'linear-message-edit',
  'linear-message-favorite',
  'linear-message-minus',
  'linear-message-notif',
  'linear-message-programming',
  'linear-message-question',
  'linear-message-remove',
  'linear-message-search',
  'linear-message-square',
  'linear-message-text-1',
  'linear-message-text',
  'linear-message-tick',
  'linear-message-time',
  'linear-message',
  'linear-messages-1',
  'linear-messages-2',
  'linear-messages-3',
  'linear-messages',
  'linear-messenger',
  'linear-microscope',
  'linear-milk',
  'linear-minus-cirlce',
  'linear-minus-square',
  'linear-minus',
  'linear-mirror',
  'linear-mirroring-screen',
  'linear-mobile-programming',
  'linear-mobile',
  'linear-monero',
  'linear-money-2',
  'linear-money-3',
  'linear-money-4',
  'linear-money-add',
  'linear-money-change',
  'linear-money-forbidden',
  'linear-money-recive',
  'linear-money-remove',
  'linear-money-send',
  'linear-money-tick',
  'linear-money-time',
  'linear-money',
  'linear-moneys',
  'linear-monitor-mobbile',
  'linear-monitor-recorder',
  'linear-monitor',
  'linear-moon',
  'linear-more-2',
  'linear-more-circle',
  'linear-more-square',
  'linear-more',
  'linear-mouse-circle',
  'linear-mouse-square',
  'linear-mouse',
  'linear-music-play',
  'linear-nebulas',
  'linear-nem',
  'linear-nexo',
  'linear-note-1',
  'linear-note-2',
  'linear-note-21',
  'linear-note-add',
  'linear-note-favorite',
  'linear-note-remove',
  'linear-note-text',
  'linear-note',
  'linear-notification-1',
  'linear-notification-bing',
  'linear-notification-circle',
  'linear-notification-favorite',
  'linear-notification-status',
  'linear-notification',
  'linear-ocean-protocol',
  'linear-okb',
  'linear-omega-circle-1',
  'linear-omega-circle',
  'linear-omega-square-1',
  'linear-omega-square',
  'linear-ontology',
  'linear-paintbucket',
  'linear-paperclip-2',
  'linear-paperclip',
  'linear-password-check',
  'linear-path-2',
  'linear-path-square',
  'linear-path',
  'linear-paypal',
  'linear-pen-add-1',
  'linear-pen-add',
  'linear-pen-close-1',
  'linear-pen-close',
  'linear-pen-remove-1',
  'linear-pen-remove',
  'linear-pen-tool-1',
  'linear-pen-tool-2-1',
  'linear-pen-tool-2',
  'linear-pen-tool',
  'linear-people',
  'linear-percentage-square',
  'linear-personalcard',
  'linear-pet',
  'linear-pharagraphspacing',
  'linear-photoshop',
  'linear-picture-frame',
  'linear-polkadot',
  'linear-polygon',
  'linear-polyswarm',
  'linear-presention-chart',
  'linear-printer-slash',
  'linear-printer',
  'linear-profile-2user',
  'linear-profile-add',
  'linear-profile-circle',
  'linear-profile-delete',
  'linear-profile-remove',
  'linear-profile-tick',
  'linear-profile',
  'linear-programming-arrow',
  'linear-programming-arrows',
  'linear-python',
  'linear-quant',
  'linear-quote-down-circle',
  'linear-quote-down-square',
  'linear-quote-down',
  'linear-quote-up-circle',
  'linear-quote-up-square',
  'linear-quote-up',
  'linear-radar-1',
  'linear-radar-2',
  'linear-radar',
  'linear-ram-2',
  'linear-ram',
  'linear-ranking-1',
  'linear-ranking',
  'linear-receipt-1',
  'linear-receipt-2-1',
  'linear-receipt-2',
  'linear-receipt-add',
  'linear-receipt-discount',
  'linear-receipt-disscount',
  'linear-receipt-edit',
  'linear-receipt-item',
  'linear-receipt-minus',
  'linear-receipt-search',
  'linear-receipt-square',
  'linear-receipt-text',
  'linear-receipt',
  'linear-receive-square-2',
  'linear-receive-square',
  'linear-received',
  'linear-recovery-convert',
  'linear-redo',
  'linear-refresh-2',
  'linear-refresh-circle',
  'linear-refresh-left-square',
  'linear-refresh-right-square',
  'linear-refresh-square-2',
  'linear-refresh',
  'linear-repeat-circle',
  'linear-repeat',
  'linear-reserve',
  'linear-rotate-left',
  'linear-rotate-right',
  'linear-route-square',
  'linear-routing-2',
  'linear-routing',
  'linear-row-horizontal',
  'linear-row-vertical',
  'linear-rulerpen',
  'linear-ruler',
  'linear-safe-home',
  'linear-sagittarius',
  'linear-save-2',
  'linear-save-add',
  'linear-save-minus',
  'linear-save-remove',
  'linear-scan-barcode',
  'linear-scan',
  'linear-scanner',
  'linear-scanning',
  'linear-scissor-1',
  'linear-scissor',
  'linear-scroll',
  'linear-search-favorite-1',
  'linear-search-favorite',
  'linear-search-normal-1',
  'linear-search-normal',
  'linear-search-status-1',
  'linear-search-status',
  'linear-search-zoom-in-1',
  'linear-search-zoom-in',
  'linear-search-zoom-out-1',
  'linear-search-zoom-out',
  'linear-security-card',
  'linear-security-safe',
  'linear-security-time',
  'linear-security-user',
  'linear-security',
  'linear-selector',
  'linear-send-2',
  'linear-send-sqaure-2',
  'linear-send-square',
  'linear-send',
  'linear-setting-2',
  'linear-setting-3',
  'linear-setting-4',
  'linear-setting-5',
  'linear-setting',
  'linear-settings',
  'linear-shapes-1',
  'linear-shapes-2',
  'linear-shapes',
  'linear-share',
  'linear-shield-cross',
  'linear-shield-search',
  'linear-shield-security',
  'linear-shield-slash',
  'linear-shield-tick',
  'linear-shield',
  'linear-ship',
  'linear-shop-add',
  'linear-shop-remove',
  'linear-shop',
  'linear-shopping-bag',
  'linear-shopping-cart',
  'linear-siacoin',
  'linear-sidebar-bottom',
  'linear-sidebar-left',
  'linear-sidebar-right',
  'linear-sidebar-top',
  'linear-signpost',
  'linear-simcard-1',
  'linear-simcard-2',
  'linear-simcard',
  'linear-size',
  'linear-slack',
  'linear-slash',
  'linear-slider-horizontal-1',
  'linear-slider-horizontal',
  'linear-slider-vertical-1',
  'linear-slider-vertical',
  'linear-slider',
  'linear-smallcaps',
  'linear-smart-car',
  'linear-smart-home',
  'linear-smileys',
  'linear-sms-edit',
  'linear-sms-notification',
  'linear-sms-search',
  'linear-sms-star',
  'linear-sms-tracking',
  'linear-sms',
  'linear-snapchat',
  'linear-solana',
  'linear-sort',
  'linear-sound',
  'linear-speaker',
  'linear-speedometer',
  'linear-spotify',
  'linear-stacks',
  'linear-star-1',
  'linear-star-slash',
  'linear-star',
  'linear-status-up',
  'linear-status',
  'linear-stellar',
  'linear-sticker',
  'linear-stickynote',
  'linear-story',
  'linear-strongbox-2',
  'linear-strongbox',
  'linear-sun-1',
  'linear-sun-fog',
  'linear-sun',
  'linear-tag-2',
  'linear-tag-cross',
  'linear-tag-right',
  'linear-tag-user',
  'linear-tag',
  'linear-task-square',
  'linear-task',
  'linear-teacher',
  'linear-tenx',
  'linear-tether',
  'linear-text-block',
  'linear-text-bold',
  'linear-text-italic',
  'linear-text-underline',
  'linear-text',
  'linear-textalign-center',
  'linear-textalign-justifycenter',
  'linear-textalign-justifyleft',
  'linear-textalign-justifyright',
  'linear-textalign-left',
  'linear-textalign-right',
  'linear-the-graph',
  'linear-theta',
  'linear-thorchain',
  'linear-tick-circle',
  'linear-tick-square',
  'linear-ticket-2',
  'linear-ticket-discount',
  'linear-ticket-expired',
  'linear-ticket-star',
  'linear-ticket',
  'linear-timer-1',
  'linear-timer-pause',
  'linear-timer-start',
  'linear-timer',
  'linear-toggle-off-circle',
  'linear-toggle-off',
  'linear-toggle-on-circle',
  'linear-toggle-on',
  'linear-trade',
  'linear-transaction-minus',
  'linear-translate',
  'linear-trash',
  'linear-tree',
  'linear-trello',
  'linear-trend-down',
  'linear-trend-up',
  'linear-triangle',
  'linear-trontron',
  'linear-truck-remove',
  'linear-truck-tick',
  'linear-truck-time',
  'linear-trush-square',
  'linear-twitch',
  'linear-ui8',
  'linear-undo',
  'linear-unlimited',
  'linear-unlock',
  'linear-usd-coin',
  'linear-user-add',
  'linear-user-cirlce-add',
  'linear-user-edit',
  'linear-user-minus',
  'linear-user-octagon',
  'linear-user-remove',
  'linear-user-search',
  'linear-user-square',
  'linear-user-tag',
  'linear-user-tick',
  'linear-user',
  'linear-velas',
  'linear-verify',
  'linear-vibe',
  'linear-vuesax',
  'linear-wallet-1',
  'linear-wallet-2',
  'linear-wallet-3',
  'linear-wallet-add-1',
  'linear-wallet-add',
  'linear-wallet-check',
  'linear-wallet-minus',
  'linear-wallet-money',
  'linear-wallet-remove',
  'linear-wallet-search',
  'linear-wallet',
  'linear-wanchain-1',
  'linear-wanchain',
  'linear-warning-2',
  'linear-watch-status',
  'linear-watch',
  'linear-weight',
  'linear-whatsapp',
  'linear-wifi-square',
  'linear-wifi',
  'linear-wind-2',
  'linear-wind',
  'linear-windows',
  'linear-wing',
  'linear-woman',
  'linear-xd',
  'linear-xiaomi',
  'linear-xrp',
  'linear-youtube',
  'linear-zel',
  'linear-zoom',
];

export const BOLD_ICON_NAMES: BoldIconName[] = [
  'bold-24-support',
  'bold-3d-cube-scan',
  'bold-3d-rotate',
  'bold-3d-square',
  'bold-3dcube',
  'bold-3square',
  'bold-aave',
  'bold-activity',
  'bold-add-circle',
  'bold-add-square',
  'bold-add',
  'bold-additem',
  'bold-airdrop',
  'bold-airplane-square',
  'bold-airplane',
  'bold-airpod',
  'bold-airpods',
  'bold-alarm',
  'bold-align-bottom',
  'bold-align-horizontally',
  'bold-align-left',
  'bold-align-right',
  'bold-align-vertically',
  'bold-android',
  'bold-ankr',
  'bold-apple',
  'bold-aquarius',
  'bold-archive-1',
  'bold-archive-add',
  'bold-archive-book',
  'bold-archive-minus',
  'bold-archive-slash',
  'bold-archive-tick',
  'bold-archive',
  'bold-arrange-circle-2',
  'bold-arrange-circle',
  'bold-arrange-square-2',
  'bold-arrange-square',
  'bold-arrow-2',
  'bold-arrow-3',
  'bold-arrow-bottom',
  'bold-arrow-circle-down',
  'bold-arrow-circle-left',
  'bold-arrow-circle-right',
  'bold-arrow-circle-up',
  'bold-arrow-down-1',
  'bold-arrow-down-2',
  'bold-arrow-down',
  'bold-arrow-left-1',
  'bold-arrow-left-2',
  'bold-arrow-left-3',
  'bold-arrow-left',
  'bold-arrow-right-1',
  'bold-arrow-right-2',
  'bold-arrow-right-3',
  'bold-arrow-right',
  'bold-arrow-square-down',
  'bold-arrow-square-left',
  'bold-arrow-square-right',
  'bold-arrow-square-up',
  'bold-arrow-square',
  'bold-arrow-swap-horizontal',
  'bold-arrow-swap',
  'bold-arrow-up-1',
  'bold-arrow-up-2',
  'bold-arrow-up-3',
  'bold-arrow-up',
  'bold-arrow',
  'bold-attach-circle',
  'bold-attach-square',
  'bold-audio-square',
  'bold-augur',
  'bold-autobrightness',
  'bold-autonio',
  'bold-avalanche',
  'bold-award',
  'bold-back-square',
  'bold-backward-10-seconds',
  'bold-backward-15-seconds',
  'bold-backward-5-seconds',
  'bold-backward-item',
  'bold-backward',
  'bold-bag-2',
  'bold-bag-cross-1',
  'bold-bag-cross',
  'bold-bag-happy',
  'bold-bag-tick-2',
  'bold-bag-tick',
  'bold-bag-timer',
  'bold-bag',
  'bold-bank',
  'bold-barcode',
  'bold-battery-charging',
  'bold-battery-disable',
  'bold-battery-empty-1',
  'bold-battery-empty',
  'bold-battery-full',
  'bold-be',
  'bold-bezier',
  'bold-bill',
  'bold-binance-coin',
  'bold-binance-usd',
  'bold-bitcoin',
  'bold-bitcoin-card',
  'bold-bitcoin-convert',
  'bold-bitcoin-refresh',
  'bold-blend-2',
  'bold-blend',
  'bold-blogger',
  'bold-bluetooth-2',
  'bold-bluetooth-circle',
  'bold-bluetooth-rectangle',
  'bold-bluetooth',
  'bold-blur',
  'bold-book-1',
  'bold-book-saved',
  'bold-book-square',
  'bold-book',
  'bold-bookmark-2',
  'bold-bookmark',
  'bold-bootsrap',
  'bold-box-1',
  'bold-box-2',
  'bold-box-add',
  'bold-box-remove',
  'bold-box-search',
  'bold-box-tick',
  'bold-box-time',
  'bold-box',
  'bold-briefcase',
  'bold-brifecase-cross',
  'bold-brifecase-tick',
  'bold-brifecase-timer',
  'bold-broom',
  'bold-brush-1',
  'bold-brush-2',
  'bold-brush-3',
  'bold-brush-4',
  'bold-brush',
  'bold-bubble',
  'bold-bucket-circle',
  'bold-bucket-square',
  'bold-bucket',
  'bold-building-3',
  'bold-building-4',
  'bold-building',
  'bold-buildings-2',
  'bold-buildings',
  'bold-buliding',
  'bold-bus',
  'bold-buy-crypto',
  'bold-cake',
  'bold-calculator',
  'bold-calendar-1',
  'bold-calendar-2',
  'bold-calendar-add',
  'bold-calendar-circle',
  'bold-calendar-edit',
  'bold-calendar-remove',
  'bold-calendar-search',
  'bold-calendar-tick',
  'bold-calendar',
  'bold-call-add',
  'bold-call-calling',
  'bold-call-incoming',
  'bold-call-minus',
  'bold-call-outgoing',
  'bold-call-received',
  'bold-call-remove',
  'bold-call-slash',
  'bold-call',
  'bold-camera-slash',
  'bold-camera',
  'bold-candle-2',
  'bold-candle',
  'bold-car',
  'bold-card-add',
  'bold-card-coin',
  'bold-card-edit',
  'bold-card-pos',
  'bold-card-receive',
  'bold-card-remove-1',
  'bold-card-remove',
  'bold-card-send',
  'bold-card-slash',
  'bold-card-tick-1',
  'bold-card-tick',
  'bold-card',
  'bold-cardano',
  'bold-cards',
  'bold-category-2',
  'bold-category',
  'bold-cd',
  'bold-celo',
  'bold-celsius',
  'bold-chainlink',
  'bold-chart-1',
  'bold-chart-2',
  'bold-chart-21',
  'bold-chart-fail',
  'bold-chart-square',
  'bold-chart-success',
  'bold-chart',
  'bold-check',
  'bold-chrome',
  'bold-civic',
  'bold-clipboard-close',
  'bold-clipboard-export',
  'bold-clipboard-import',
  'bold-clipboard-text',
  'bold-clipboard-tick',
  'bold-clipboard',
  'bold-clock-1',
  'bold-clock',
  'bold-close-circle',
  'bold-close-square',
  'bold-cloud-add',
  'bold-cloud-change',
  'bold-cloud-connection',
  'bold-cloud-cross',
  'bold-cloud-drizzle',
  'bold-cloud-fog',
  'bold-cloud-lightning',
  'bold-cloud-minus',
  'bold-cloud-notif',
  'bold-cloud-plus',
  'bold-cloud-remove',
  'bold-cloud-snow',
  'bold-cloud-sunny',
  'bold-cloud',
  'bold-code-1',
  'bold-code-circle',
  'bold-code',
  'bold-coffee',
  'bold-coin-1',
  'bold-coin',
  'bold-color-swatch',
  'bold-colorfilter',
  'bold-colors-square',
  'bold-command-square',
  'bold-command',
  'bold-component',
  'bold-computing',
  'bold-convert-3d-cube',
  'bold-convert-card',
  'bold-convert',
  'bold-convertshape-2',
  'bold-convertshape',
  'bold-copy-success',
  'bold-copy',
  'bold-copyright',
  'bold-courthouse',
  'bold-cpu-charge',
  'bold-cpu-setting',
  'bold-cpu',
  'bold-creative-commons',
  'bold-crop',
  'bold-crown-1',
  'bold-crown',
  'bold-cup',
  'bold-dai',
  'bold-danger',
  'bold-dash',
  'bold-data-2',
  'bold-data',
  'bold-decred',
  'bold-dent',
  'bold-designtools',
  'bold-device-message',
  'bold-devices',
  'bold-diagram',
  'bold-diamonds',
  'bold-direct-down',
  'bold-direct-inbox',
  'bold-direct-left',
  'bold-direct-normal',
  'bold-direct-notification',
  'bold-direct-right',
  'bold-direct-send',
  'bold-direct-up',
  'bold-direct',
  'bold-directbox-default',
  'bold-directbox-notif',
  'bold-directbox-receive',
  'bold-directbox-send',
  'bold-discount-circle',
  'bold-discount-shape',
  'bold-discover',
  'bold-dislike',
  'bold-document-cloud',
  'bold-document-code-2',
  'bold-document-code',
  'bold-document-copy',
  'bold-document-download',
  'bold-document-favorite',
  'bold-document-filter',
  'bold-document-forward',
  'bold-document-like',
  'bold-document-normal',
  'bold-document-previous',
  'bold-document-sketch',
  'bold-document-text-1',
  'bold-document-text',
  'bold-document-upload',
  'bold-document',
  'bold-dollar-circle',
  'bold-dollar-square',
  'bold-dribbble',
  'bold-driver-2',
  'bold-driver-refresh',
  'bold-driver',
  'bold-driving',
  'bold-drop',
  'bold-dropbox',
  'bold-edit-2',
  'bold-edit',
  'bold-educare',
  'bold-electricity',
  'bold-element-2',
  'bold-element-3',
  'bold-element-4',
  'bold-element-equal',
  'bold-element-plus',
  'bold-emercoin',
  'bold-emoji-happy',
  'bold-emoji-normal',
  'bold-emoji-sad',
  'bold-empty-wallet-add',
  'bold-empty-wallet-change',
  'bold-empty-wallet-remove',
  'bold-empty-wallet-tick',
  'bold-empty-wallet-time',
  'bold-empty-wallet',
  'bold-enjin-coin',
  'bold-eos',
  'bold-eraser',
  'bold-ethereum',
  'bold-ethereum-classic',
  'bold-export-1',
  'bold-export-2',
  'bold-export-3',
  'bold-export',
  'bold-external-drive',
  'bold-eye-slash',
  'bold-eye',
  'bold-facebook',
  'bold-fatrows',
  'bold-favorite-chart',
  'bold-figma-1',
  'bold-figma',
  'bold-filter-add',
  'bold-filter-edit',
  'bold-filter-remove',
  'bold-filter-search',
  'bold-filter-square',
  'bold-filter-tick',
  'bold-filter',
  'bold-finger-cricle',
  'bold-finger-scan',
  'bold-firstline',
  'bold-flag-2',
  'bold-flag',
  'bold-flash-circle-1',
  'bold-flash-circle',
  'bold-flash-slash',
  'bold-flash',
  'bold-folder-2',
  'bold-folder-add',
  'bold-folder-cloud',
  'bold-folder-connection',
  'bold-folder-cross',
  'bold-folder-favorite',
  'bold-folder-minus',
  'bold-folder-open',
  'bold-folder',
  'bold-forbidden-2',
  'bold-forbidden',
  'bold-format-circle',
  'bold-format-square',
  'bold-forward-10-seconds',
  'bold-forward-15-seconds',
  'bold-forward-5-seconds',
  'bold-forward-item',
  'bold-forward-square',
  'bold-forward',
  'bold-frame-1',
  'bold-frame-2',
  'bold-frame',
  'bold-framer',
  'bold-ftx-token',
  'bold-gallery-add',
  'bold-gallery-edit',
  'bold-gallery-export',
  'bold-gallery-favorite',
  'bold-gallery-import',
  'bold-gallery-remove',
  'bold-gallery-slash',
  'bold-gallery-tick',
  'bold-gallery',
  'bold-game',
  'bold-gameboy',
  'bold-gas-station',
  'bold-gemini-2',
  'bold-gemini',
  'bold-ghost',
  'bold-gift',
  'bold-glass-1',
  'bold-glass',
  'bold-global-edit',
  'bold-global-refresh',
  'bold-global-search',
  'bold-global',
  'bold-google-1',
  'bold-google-play',
  'bold-google',
  'bold-gps-slash',
  'bold-gps',
  'bold-grammerly',
  'bold-graph',
  'bold-grid-1',
  'bold-grid-2',
  'bold-grid-3',
  'bold-grid-4',
  'bold-grid-5',
  'bold-grid-6',
  'bold-grid-7',
  'bold-grid-8',
  'bold-grid-9',
  'bold-grid-edit',
  'bold-grid-eraser',
  'bold-grid-lock',
  'bold-happyemoji',
  'bold-harmony',
  'bold-hashtag-down',
  'bold-hashtag-up',
  'bold-hashtag',
  'bold-headphone',
  'bold-headphones',
  'bold-health',
  'bold-heart-add',
  'bold-heart-circle',
  'bold-heart-edit',
  'bold-heart-remove',
  'bold-heart-search',
  'bold-heart-slash',
  'bold-heart-tick',
  'bold-heart',
  'bold-hedera-hashgraph',
  'bold-hex',
  'bold-hierarchy-2',
  'bold-hierarchy-3',
  'bold-hierarchy-square-2',
  'bold-hierarchy-square-3',
  'bold-hierarchy-square',
  'bold-hierarchy',
  'bold-home-1',
  'bold-home-2',
  'bold-home-hashtag',
  'bold-home-trend-down',
  'bold-home-trend-up',
  'bold-home-wifi',
  'bold-home',
  'bold-hospital',
  'bold-house-2',
  'bold-house',
  'bold-html-3',
  'bold-html-5',
  'bold-huobi-token',
  'bold-icon',
  'bold-icon-1',
  'bold-illustrator',
  'bold-image',
  'bold-import-1',
  'bold-import-2',
  'bold-import-3',
  'bold-import',
  'bold-info-circle',
  'bold-information',
  'bold-instagram',
  'bold-iost',
  'bold-java-script',
  'bold-js',
  'bold-judge',
  'bold-kanban',
  'bold-key-square',
  'bold-key',
  'bold-keyboard-open',
  'bold-keyboard',
  'bold-kyber-network',
  'bold-lamp-1',
  'bold-lamp-charge',
  'bold-lamp-on',
  'bold-lamp-slash',
  'bold-lamp',
  'bold-language-circle',
  'bold-language-square',
  'bold-layer',
  'bold-level',
  'bold-lifebuoy',
  'bold-like-1',
  'bold-like-dislike',
  'bold-like-shapes',
  'bold-like-tag',
  'bold-like',
  'bold-link-1',
  'bold-link-2',
  'bold-link-21',
  'bold-link-circle',
  'bold-link-square',
  'bold-link',
  'bold-litecoin',
  'bold-location-add',
  'bold-location-cross',
  'bold-location-minus',
  'bold-location-slash',
  'bold-location-tick',
  'bold-location',
  'bold-lock-1',
  'bold-lock-circle',
  'bold-lock-slash',
  'bold-lock',
  'bold-login-1',
  'bold-login',
  'bold-logout-1',
  'bold-logout',
  'bold-lovely',
  'bold-magic-star',
  'bold-magicpen',
  'bold-main-component',
  'bold-maker',
  'bold-man',
  'bold-map-1',
  'bold-map',
  'bold-mask-1',
  'bold-mask-2',
  'bold-mask',
  'bold-math',
  'bold-maximize-1',
  'bold-maximize-2',
  'bold-maximize-3',
  'bold-maximize-4',
  'bold-maximize-circle',
  'bold-maximize',
  'bold-medal-star',
  'bold-medal',
  'bold-menu-1',
  'bold-menu-board',
  'bold-menu',
  'bold-message-2',
  'bold-message-add-1',
  'bold-message-add',
  'bold-message-circle',
  'bold-message-edit',
  'bold-message-favorite',
  'bold-message-minus',
  'bold-message-notif',
  'bold-message-programming',
  'bold-message-question',
  'bold-message-remove',
  'bold-message-search',
  'bold-message-square',
  'bold-message-text-1',
  'bold-message-text',
  'bold-message-tick',
  'bold-message-time',
  'bold-message',
  'bold-messages-1',
  'bold-messages-2',
  'bold-messages-3',
  'bold-messages',
  'bold-messenger',
  'bold-microphone-2',
  'bold-microphone-slash-1',
  'bold-microphone-slash',
  'bold-microphone',
  'bold-microscope',
  'bold-milk',
  'bold-mini-music-sqaure',
  'bold-minus-cirlce',
  'bold-minus-square',
  'bold-minus',
  'bold-mirror',
  'bold-mirroring-screen',
  'bold-mobile-programming',
  'bold-mobile',
  'bold-monero',
  'bold-money-2',
  'bold-money-3',
  'bold-money-4',
  'bold-money-add',
  'bold-money-change',
  'bold-money-forbidden',
  'bold-money-recive',
  'bold-money-remove',
  'bold-money-send',
  'bold-money-tick',
  'bold-money-time',
  'bold-money',
  'bold-moneys',
  'bold-monitor-mobbile',
  'bold-monitor-recorder',
  'bold-monitor',
  'bold-moon',
  'bold-more-2',
  'bold-more-circle',
  'bold-more-square',
  'bold-more',
  'bold-mouse-1',
  'bold-mouse-circle',
  'bold-mouse-square',
  'bold-mouse',
  'bold-music-circle',
  'bold-music-dashboard',
  'bold-music-filter',
  'bold-music-library-2',
  'bold-music-play',
  'bold-music-playlist',
  'bold-music-square-add',
  'bold-music-square-remove',
  'bold-music-square-search',
  'bold-music-square',
  'bold-music',
  'bold-musicnote',
  'bold-nebulas',
  'bold-nem',
  'bold-nexo',
  'bold-next',
  'bold-note-1',
  'bold-note-2',
  'bold-note-add',
  'bold-note-favorite',
  'bold-note-remove',
  'bold-note-square',
  'bold-note-text',
  'bold-note',
  'bold-notification-1',
  'bold-notification-bing',
  'bold-notification-favorite',
  'bold-notification-status',
  'bold-notification',
  'bold-ocean-protocol',
  'bold-okb',
  'bold-omega-circle',
  'bold-omega-square',
  'bold-ontology',
  'bold-paintbucket',
  'bold-paperclip-2',
  'bold-paperclip',
  'bold-password-check',
  'bold-path-2',
  'bold-path-square',
  'bold-path',
  'bold-pause-circle',
  'bold-pause',
  'bold-paypal',
  'bold-pen-add',
  'bold-pen-close',
  'bold-pen-remove',
  'bold-pen-tool-2',
  'bold-pen-tool',
  'bold-people',
  'bold-percentage-circle',
  'bold-percentage-square',
  'bold-personalcard',
  'bold-pet',
  'bold-pharagraphspacing',
  'bold-photoshop',
  'bold-picture-frame',
  'bold-play-add',
  'bold-play-circle',
  'bold-play-cricle',
  'bold-play-remove',
  'bold-play',
  'bold-polkadot',
  'bold-polygon',
  'bold-polyswarm',
  'bold-presention-chart',
  'bold-previous',
  'bold-printer-slash',
  'bold-printer',
  'bold-profile-2user',
  'bold-profile-add',
  'bold-profile-circle',
  'bold-profile-delete',
  'bold-profile-remove',
  'bold-profile-tick',
  'bold-programming-arrow',
  'bold-programming-arrows',
  'bold-python',
  'bold-quant',
  'bold-quote-down-circle',
  'bold-quote-down-square',
  'bold-quote-down',
  'bold-quote-up-circle',
  'bold-quote-up-square',
  'bold-quote-up',
  'bold-radar-1',
  'bold-radar-2',
  'bold-radar',
  'bold-radio',
  'bold-ram-2',
  'bold-ram',
  'bold-ranking-1',
  'bold-ranking',
  'bold-receipt-1',
  'bold-receipt-2-1',
  'bold-receipt-2',
  'bold-receipt-add',
  'bold-receipt-discount',
  'bold-receipt-disscount',
  'bold-receipt-edit',
  'bold-receipt-item',
  'bold-receipt-minus',
  'bold-receipt-search',
  'bold-receipt-square',
  'bold-receipt-text',
  'bold-receipt',
  'bold-receive-square-2',
  'bold-receive-square',
  'bold-received',
  'bold-record-circle',
  'bold-record',
  'bold-recovery-convert',
  'bold-redo',
  'bold-refresh-2',
  'bold-refresh-circle',
  'bold-refresh-left-square',
  'bold-refresh-right-square',
  'bold-refresh-square-2',
  'bold-refresh',
  'bold-repeat-circle',
  'bold-repeat',
  'bold-repeate-music',
  'bold-repeate-one',
  'bold-reserve',
  'bold-rotate-left',
  'bold-rotate-right',
  'bold-route-square',
  'bold-routing-2',
  'bold-routing',
  'bold-row-horizontal',
  'bold-row-vertical',
  'bold-rulerpen',
  'bold-ruler',
  'bold-safe-home',
  'bold-sagittarius',
  'bold-save-2',
  'bold-save-add',
  'bold-save-minus',
  'bold-save-remove',
  'bold-scan-barcode',
  'bold-scan',
  'bold-scanner',
  'bold-scanning',
  'bold-scissor',
  'bold-screenmirroring',
  'bold-scroll',
  'bold-search-favorite-1',
  'bold-search-favorite',
  'bold-search-normal-1',
  'bold-search-normal',
  'bold-search-status-1',
  'bold-search-status',
  'bold-search-zoom-in-1',
  'bold-search-zoom-in',
  'bold-search-zoom-out-1',
  'bold-search-zoom-out',
  'bold-security-card',
  'bold-security-safe',
  'bold-security-time',
  'bold-security-user',
  'bold-security',
  'bold-send-2',
  'bold-send-sqaure-2',
  'bold-send-square',
  'bold-send',
  'bold-setting-2',
  'bold-setting-3',
  'bold-setting-4',
  'bold-setting-5',
  'bold-setting',
  'bold-settings',
  'bold-shapes-1',
  'bold-shapes',
  'bold-share',
  'bold-shield-cross',
  'bold-shield-search',
  'bold-shield-security',
  'bold-shield-slash',
  'bold-shield-tick',
  'bold-ship',
  'bold-shop-add',
  'bold-shop-remove',
  'bold-shop',
  'bold-shopping-bag',
  'bold-shopping-cart',
  'bold-shuffle',
  'bold-siacoin',
  'bold-sidebar-bottom',
  'bold-sidebar-left',
  'bold-sidebar-right',
  'bold-sidebar-top',
  'bold-signpost',
  'bold-simcard-1',
  'bold-simcard-2',
  'bold-simcard',
  'bold-size',
  'bold-slack',
  'bold-slash',
  'bold-slider-horizontal-1',
  'bold-slider-horizontal',
  'bold-slider-vertical-1',
  'bold-slider-vertical',
  'bold-slider',
  'bold-smallcaps',
  'bold-smart-car',
  'bold-smart-home',
  'bold-smileys',
  'bold-sms-edit',
  'bold-sms-notification',
  'bold-sms-search',
  'bold-sms-star',
  'bold-sms-tracking',
  'bold-sms',
  'bold-snapchat',
  'bold-solana',
  'bold-sort',
  'bold-sound',
  'bold-speaker',
  'bold-speedometer',
  'bold-spotify',
  'bold-stacks',
  'bold-star-1',
  'bold-star-slash',
  'bold-star',
  'bold-status-up',
  'bold-status',
  'bold-stellar',
  'bold-sticker',
  'bold-stickynote',
  'bold-stop-circle',
  'bold-stop',
  'bold-story',
  'bold-strongbox-2',
  'bold-strongbox',
  'bold-subtitle',
  'bold-sun-1',
  'bold-sun-fog',
  'bold-sun',
  'bold-tag-2',
  'bold-tag-cross',
  'bold-tag-right',
  'bold-tag-user',
  'bold-tag',
  'bold-task-square',
  'bold-task',
  'bold-teacher',
  'bold-tenx',
  'bold-tether',
  'bold-text-block',
  'bold-text-bold',
  'bold-text-italic',
  'bold-text-underline',
  'bold-text',
  'bold-textalign-center',
  'bold-textalign-justifycenter',
  'bold-textalign-justifyleft',
  'bold-textalign-justifyright',
  'bold-textalign-left',
  'bold-textalign-right',
  'bold-the-graph',
  'bold-theta',
  'bold-thorchain',
  'bold-tick-circle',
  'bold-tick-square',
  'bold-ticket-2',
  'bold-ticket-discount',
  'bold-ticket-expired',
  'bold-ticket-star',
  'bold-ticket',
  'bold-timer-1',
  'bold-timer-pause',
  'bold-timer-start',
  'bold-timer',
  'bold-toggle-off-circle',
  'bold-toggle-off',
  'bold-toggle-on-circle',
  'bold-toggle-on',
  'bold-trade',
  'bold-transaction-minus',
  'bold-translate',
  'bold-trash',
  'bold-tree',
  'bold-trello',
  'bold-trend-down',
  'bold-trend-up',
  'bold-triangle',
  'bold-trontron',
  'bold-truck-fast',
  'bold-truck-remove',
  'bold-truck-tick',
  'bold-truck-time',
  'bold-truck',
  'bold-trush-square',
  'bold-twitch',
  'bold-ui8',
  'bold-undo',
  'bold-unlimited',
  'bold-unlock',
  'bold-usd-coin',
  'bold-user-add',
  'bold-user-cirlce-add',
  'bold-user-edit',
  'bold-user-minus',
  'bold-user-octagon',
  'bold-user-remove',
  'bold-user-search',
  'bold-user-square',
  'bold-user-tag',
  'bold-user-tick',
  'bold-user',
  'bold-velas',
  'bold-verify',
  'bold-vibe',
  'bold-video-add',
  'bold-video-circle',
  'bold-video-horizontal',
  'bold-video-octagon',
  'bold-video-play',
  'bold-video-remove',
  'bold-video-slash',
  'bold-video-square',
  'bold-video-tick',
  'bold-video-time',
  'bold-video-vertical',
  'bold-video',
  'bold-voice-cricle',
  'bold-voice-square',
  'bold-volume-cross',
  'bold-volume-high',
  'bold-volume-low-1',
  'bold-volume-low',
  'bold-volume-mute',
  'bold-volume-slash',
  'bold-volume-up',
  'bold-vuesax',
  'bold-wallet-1',
  'bold-wallet-2',
  'bold-wallet-3',
  'bold-wallet-add-1',
  'bold-wallet-add',
  'bold-wallet-check',
  'bold-wallet-minus',
  'bold-wallet-money',
  'bold-wallet-remove',
  'bold-wallet-search',
  'bold-wallet',
  'bold-wanchain-1',
  'bold-wanchain',
  'bold-warning-2',
  'bold-watch-status',
  'bold-watch',
  'bold-weight-1',
  'bold-weight',
  'bold-whatsapp',
  'bold-wifi-square',
  'bold-wifi',
  'bold-wind-2',
  'bold-wind',
  'bold-windows',
  'bold-wing',
  'bold-woman',
  'bold-xd',
  'bold-xiaomi',
  'bold-xrp',
  'bold-youtube',
  'bold-zel',
  'bold-zoom',
];

export const ALL_ICON_NAMES: IconName[] = [...LINEAR_ICON_NAMES, ...BOLD_ICON_NAMES];
