#!/usr/bin/env node
/**
 * scripts/generate-sprite.cjs
 * @axioledger/axio-design-system v6.0.0
 *
 * Scans /root/asset/icon/{linear,bold}/*.svg (Axioledger icon asset repo)
 * and produces:
 *   public/sprites/icons.svg          — SVG sprite sheet
 *   src/components/Icon/icon.types.ts — TypeScript union types (auto-generated)
 *
 * Only Axioledger-specific icons are bundled by default.
 * The full 1,897-icon library from /root/asset/icon is available but NOT
 * shipped in the bundle — consumers fetch icons via SVG <use> references,
 * so zero JS bundle cost.
 *
 * Re-run: pnpm prep:icons
 */

const fs   = require('fs');
const path = require('path');

// ─── Paths ────────────────────────────────────────────────────────────────────
const ICON_ROOT  = path.resolve('/root/asset/icon');
const SPRITE_OUT = path.resolve(__dirname, '../public/sprites/icons.svg');
const TYPES_OUT  = path.resolve(__dirname, '../src/components/Icon/icon.types.ts');
const VARIANTS   = ['linear', 'bold'];

// ─── Sanitize filename → icon name ───────────────────────────────────────────
function sanitize(filename) {
  return filename
    .replace(/\.svg$/i, '')
    .toLowerCase()
    .replace(/\s*\([^)]*\)/g, '')
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

// ─── Strip hard-coded colours (inherit currentColor) ─────────────────────────
function stripColors(svgContent) {
  return svgContent
    .replace(/<svg([^>]*)>/i, (match, attrs) => {
      attrs = attrs.replace(/\s*(width|height)="[^"]*"/gi, '');
      return `<svg${attrs}>`;
    })
    .replace(/fill="(?!none")[^"]*"/gi, 'fill="currentColor"')
    .replace(/stroke="(?!none")[^"]*"/gi, 'stroke="currentColor"')
    .replace(/style="[^"]*?(fill|stroke):[^;}"]*;?[^"]*"/gi, '');
}

// ─── Extract inner SVG body ───────────────────────────────────────────────────
function extractBody(svgContent) {
  const inner = svgContent.replace(/<\?xml[^>]*>/gi, '');
  const match = inner.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
  return match ? match[1].trim() : '';
}

// ─── Main ─────────────────────────────────────────────────────────────────────
const symbolLines = [];
const allIconNames = [];

for (const variant of VARIANTS) {
  const dir = path.join(ICON_ROOT, variant);
  if (!fs.existsSync(dir)) {
    console.warn(`[warn] Icon directory not found: ${dir}`);
    console.warn(`       Sprite will be empty. Place icons in /root/asset/icon/${variant}/*.svg`);
    continue;
  }

  const files = fs.readdirSync(dir).filter(f => f.endsWith('.svg')).sort();
  const seenNames = new Set();
  let count = 0;

  for (const file of files) {
    const name = sanitize(file);
    if (!name) { console.warn(`[skip] Cannot sanitize: ${file}`); continue; }

    const id = `${variant}-${name}`;
    if (seenNames.has(id)) { console.warn(`[dedup] ${id} (${file})`); continue; }
    seenNames.add(id);

    const raw     = fs.readFileSync(path.join(dir, file), 'utf8');
    const cleaned = stripColors(raw);
    const body    = extractBody(cleaned);
    const viewBoxMatch = raw.match(/viewBox="([^"]*)"/i);
    const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';

    symbolLines.push(`  <symbol id="${id}" viewBox="${viewBox}">`);
    symbolLines.push(`    ${body}`);
    symbolLines.push(`  </symbol>`);
    allIconNames.push({ variant, name });
    count++;
  }

  console.log(`[${variant}] ${count} icons processed`);
}

// ─── Write sprite SVG ─────────────────────────────────────────────────────────
const now = new Date().toISOString();
const sprite = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<!-- @axioledger/axio-design-system — SVG Sprite Sheet -->`,
  `<!-- Generated: ${now} | Total: ${allIconNames.length} symbols -->`,
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">`,
  ...symbolLines,
  `</svg>`,
].join('\n');

fs.mkdirSync(path.dirname(SPRITE_OUT), { recursive: true });
fs.writeFileSync(SPRITE_OUT, sprite, 'utf8');
console.log(`\n✅ Sprite  → ${SPRITE_OUT} (${allIconNames.length} symbols)`);

// ─── Write icon.types.ts ──────────────────────────────────────────────────────
const linearNames = allIconNames.filter(i => i.variant === 'linear');
const boldNames   = allIconNames.filter(i => i.variant === 'bold');

// Build union type lines — if empty, produce a never-equivalent placeholder
const linearLines = linearNames.length
  ? linearNames.map((i, idx) => `${idx === 0 ? '  ' : '  | '}'linear-${i.name}'`)
  : ["  'linear-placeholder'  /* no icons found — run pnpm prep:icons */"];

const boldLines = boldNames.length
  ? boldNames.map((i, idx) => `${idx === 0 ? '  ' : '  | '}'bold-${i.name}'`)
  : ["  'bold-placeholder'  /* no icons found — run pnpm prep:icons */"];

const tsContent = [
  `// icon.types.ts — AUTO-GENERATED by scripts/generate-sprite.cjs`,
  `// DO NOT EDIT MANUALLY. Re-run: pnpm prep:icons`,
  `// Generated: ${now}`,
  `// Total: ${allIconNames.length} (${linearNames.length} linear + ${boldNames.length} bold)`,
  ``,
  `export type LinearIconName =`,
  ...linearLines,
  `  ;`,
  ``,
  `export type BoldIconName =`,
  ...boldLines,
  `  ;`,
  ``,
  `/** Union of all available icon IDs in the AXIO sprite sheet */`,
  `export type IconName = LinearIconName | BoldIconName;`,
  ``,
  `export const LINEAR_ICON_NAMES: LinearIconName[] = [`,
  ...linearNames.map(i => `  'linear-${i.name}',`),
  `];`,
  ``,
  `export const BOLD_ICON_NAMES: BoldIconName[] = [`,
  ...boldNames.map(i => `  'bold-${i.name}',`),
  `];`,
  ``,
  `export const ALL_ICON_NAMES: IconName[] = [...LINEAR_ICON_NAMES, ...BOLD_ICON_NAMES];`,
  ``,
].join('\n');

fs.mkdirSync(path.dirname(TYPES_OUT), { recursive: true });
fs.writeFileSync(TYPES_OUT, tsContent, 'utf8');
console.log(`✅ Types   → ${TYPES_OUT}`);
