'use strict';
/**
 * @axioledger/axq-sdk — AXIOLEDGER TypeScript/JS Client SDK
 *
 * Real on-chain reads via viem createPublicClient.
 * Write operations use a walletClient passed at call-time so this SDK
 * stays framework-agnostic (works in Next.js, Node, or CLI).
 */

const { createPublicClient, http, encodeAbiParameters, keccak256, parseAbiParameters } = require('viem');
const { sepolia, mainnet } = require('viem/chains');
const { AXQ_TOKEN_ABI, ANS_REGISTRY_ABI } = require('./abis');

// ── Constants ──────────────────────────────────────────────────────────────

/** Supported ANS TLDs. @readonly */
const ANS_TLDS = Object.freeze(['axq', 'vpx', 'sqx', 'kpx', 'vrq']);

/** Default RPC endpoints per network. @readonly */
const DEFAULT_RPC = Object.freeze({
  mainnet:  'https://rpc.axqprotocol.axq',
  sepolia:  'https://eth-sepolia.g.alchemy.com/v2/demo',
  localnet: 'http://127.0.0.1:8545',
});

/**
 * Deterministic Anvil contract addresses (localnet only).
 * Generated by: forge script script/Deploy.s.sol:DeployLocalnet
 * These are stable as long as Anvil starts with account 0 at nonce 0.
 * @readonly
 */
const LOCALNET_CONTRACTS = Object.freeze({
  axqToken:     '0x5FbDB2315678afecb367f032d93F642f64180aa3',
  axqVesting:   '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
  axqGovernance:'0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
  rdTreasury:   '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
  // KPXRouterGateway + mock dependencies — deployed chain 31337
  kpxRouter:    '0xa513E6E4b8f2a923D98304ec87F64353C4D5C853',
  kpxVrqVerifier:'0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
  kpxDarkPool:  '0x0165878A594ca255338adfa4d48449f69242Eb8F',
  // ANS Registry — deployed chain 31337
  ansRegistry:  '0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6',
  // VRQ Validator not yet deployed on localnet
  vrqValidator: null,
  vpxOracle:    null,
});

/** Chain objects for viem. @readonly */
const CHAINS = Object.freeze({ mainnet, sepolia });

// ── AxioledgerSDK ──────────────────────────────────────────────────────────

/**
 * AXIOLEDGER SDK — main entry point.
 *
 * @example
 * const sdk = new AxioledgerSDK({
 *   rpcUrl: 'https://eth-sepolia.g.alchemy.com/v2/MY_KEY',
 *   network: 'sepolia',
 *   contracts: {
 *     axqToken:    '0x...',
 *     ansRegistry: '0x...',
 *   },
 * });
 *
 * const balance = await sdk.getBalance('0xabc…');
 * const owner   = await sdk.resolveANS('alice', 'axq');
 */
class AxioledgerSDK {
  /**
   * @param {object}  config
   * @param {string}  [config.rpcUrl]    - override RPC endpoint
   * @param {string}  [config.network]   - 'mainnet' | 'sepolia' | 'localnet'
   * @param {object}  [config.contracts] - deployed contract addresses
   * @param {string}  [config.contracts.axqToken]
   * @param {string}  [config.contracts.ansRegistry]
   * @param {string}  [config.contracts.kpxRouter]
   * @param {string}  [config.contracts.vpxOracle]
   * @param {string}  [config.contracts.vrqValidator]
   */
  constructor(config = {}) {
    const network     = config.network || 'sepolia';
    this.network      = network;
    this.rpcUrl       = config.rpcUrl || DEFAULT_RPC[network] || DEFAULT_RPC.sepolia;
    // Localnet: auto-populate known deterministic addresses if not overridden
    const networkDefaults = network === 'localnet' ? LOCALNET_CONTRACTS : {};
    this.contracts    = {
      axqToken:     null,
      ansRegistry:  null,
      kpxRouter:    null,
      vpxOracle:    null,
      vrqValidator: null,
      ...networkDefaults,
      ...config.contracts,
    };

    /** @type {import('viem').PublicClient} */
    this._client = createPublicClient({
      chain:     CHAINS[network] ?? sepolia,
      transport: http(this.rpcUrl),
    });
  }

  // ── AXQToken ──────────────────────────────────────────────────────────────

  /**
   * Get $AXQ balance for an address.
   * @param {`0x${string}`} address
   * @returns {Promise<bigint>} balance in wei (18 decimals)
   */
  async getBalance(address) {
    if (!this.contracts.axqToken) throw new Error('axqToken address not configured');
    return this._client.readContract({
      address: this.contracts.axqToken,
      abi:     AXQ_TOKEN_ABI,
      functionName: 'balanceOf',
      args:    [address],
    });
  }

  /**
   * Get total $AXQ supply.
   * @returns {Promise<bigint>}
   */
  async getTotalSupply() {
    if (!this.contracts.axqToken) throw new Error('axqToken address not configured');
    return this._client.readContract({
      address: this.contracts.axqToken,
      abi:     AXQ_TOKEN_ABI,
      functionName: 'totalSupply',
    });
  }

  /**
   * Get the allowance granted by `owner` to `spender`.
   * @param {`0x${string}`} owner
   * @param {`0x${string}`} spender
   * @returns {Promise<bigint>}
   */
  async getAllowance(owner, spender) {
    if (!this.contracts.axqToken) throw new Error('axqToken address not configured');
    return this._client.readContract({
      address: this.contracts.axqToken,
      abi:     AXQ_TOKEN_ABI,
      functionName: 'allowance',
      args:    [owner, spender],
    });
  }

  /**
   * Transfer $AXQ tokens.  Requires a walletClient with a connected account.
   * @param {import('viem').WalletClient} walletClient
   * @param {`0x${string}`} to
   * @param {bigint}        amount  in wei
   * @returns {Promise<`0x${string}`>} transaction hash
   */
  async transfer(walletClient, to, amount) {
    if (!this.contracts.axqToken) throw new Error('axqToken address not configured');
    const [account] = await walletClient.getAddresses();
    return walletClient.writeContract({
      address: this.contracts.axqToken,
      abi:     AXQ_TOKEN_ABI,
      functionName: 'transfer',
      args:    [to, amount],
      account,
    });
  }

  /**
   * Approve `spender` to use `amount` of the caller's $AXQ.
   * @param {import('viem').WalletClient} walletClient
   * @param {`0x${string}`} spender
   * @param {bigint}        amount
   * @returns {Promise<`0x${string}`>} transaction hash
   */
  async approve(walletClient, spender, amount) {
    if (!this.contracts.axqToken) throw new Error('axqToken address not configured');
    const [account] = await walletClient.getAddresses();
    return walletClient.writeContract({
      address: this.contracts.axqToken,
      abi:     AXQ_TOKEN_ABI,
      functionName: 'approve',
      args:    [spender, amount],
      account,
    });
  }

  // ── ANS Registry ──────────────────────────────────────────────────────────

  /**
   * Resolve `label.tld` to its owner address.
   * @param {string} label  e.g. "alice"
   * @param {string} tld    e.g. "axq"
   * @returns {Promise<`0x${string}`>} owner address
   */
  async resolveANS(label, tld) {
    if (!ANS_TLDS.includes(tld))       throw new Error(`Unsupported TLD: .${tld}`);
    if (!this.contracts.ansRegistry)   throw new Error('ansRegistry address not configured');
    return this._client.readContract({
      address: this.contracts.ansRegistry,
      abi:     ANS_REGISTRY_ABI,
      functionName: 'resolve',
      args:    [label, tld],
    });
  }

  /**
   * Get the resolver contract address for `label.tld`.
   * @param {string} label
   * @param {string} tld
   * @returns {Promise<`0x${string}`>}
   */
  async getResolver(label, tld) {
    if (!ANS_TLDS.includes(tld))      throw new Error(`Unsupported TLD: .${tld}`);
    if (!this.contracts.ansRegistry)  throw new Error('ansRegistry address not configured');
    return this._client.readContract({
      address: this.contracts.ansRegistry,
      abi:     ANS_REGISTRY_ABI,
      functionName: 'getResolver',
      args:    [label, tld],
    });
  }

  /**
   * Check whether a name is currently registered and active.
   * Uses the `records` view to inspect expiry without reverting.
   * @param {string} label
   * @param {string} tld
   * @returns {Promise<boolean>}
   */
  async isRegistered(label, tld) {
    if (!ANS_TLDS.includes(tld))      throw new Error(`Unsupported TLD: .${tld}`);
    if (!this.contracts.ansRegistry)  throw new Error('ansRegistry address not configured');

    // nameHash = keccak256(abi.encodePacked(keccak256(label), keccak256(tld)))
    const nameHash = keccak256(
      encodeAbiParameters(
        parseAbiParameters('bytes32, bytes32'),
        [keccak256(new TextEncoder().encode(label)), keccak256(new TextEncoder().encode(tld))]
      )
    );

    const [owner, , expiry] = await this._client.readContract({
      address: this.contracts.ansRegistry,
      abi:     ANS_REGISTRY_ABI,
      functionName: 'records',
      args:    [nameHash],
    });

    return owner !== '0x0000000000000000000000000000000000000000'
        && BigInt(expiry) > BigInt(Math.floor(Date.now() / 1000));
  }

  /**
   * Register a new ANS name.  Requires a walletClient.
   * @param {import('viem').WalletClient} walletClient
   * @param {string}          label
   * @param {string}          tld
   * @param {`0x${string}`}   resolver  address(0) if no resolver
   * @param {bigint}          fee       registration fee in wei (from tldFees())
   * @returns {Promise<`0x${string}`>} transaction hash
   */
  async registerANS(walletClient, label, tld, resolver, fee) {
    if (!ANS_TLDS.includes(tld))      throw new Error(`Unsupported TLD: .${tld}`);
    if (!this.contracts.ansRegistry)  throw new Error('ansRegistry address not configured');
    const [account] = await walletClient.getAddresses();
    return walletClient.writeContract({
      address: this.contracts.ansRegistry,
      abi:     ANS_REGISTRY_ABI,
      functionName: 'register',
      args:    [label, tld, resolver],
      value:   fee,
      account,
    });
  }

  // ── Oracle / Swap stubs (Phase 5 — remaining) ─────────────────────────────

  /**
   * Get latest VPX oracle price for an asset.
   * @param {string} _symbol  e.g. "ETH"
   * @returns {Promise<{price: bigint, timestamp: bigint, roundId: bigint}>}
   */
  async getOraclePrice(_symbol) {
    if (!this.contracts.vpxOracle) throw new Error('vpxOracle address not configured');
    throw new Error('getOraclePrice — VPX oracle ABI not yet deployed (Phase 5)');
  }

  /**
   * Estimate swap output for `amountIn` of `tokenIn` → `tokenOut`.
   * @returns {Promise<bigint>} estimated amountOut
   */
  async estimateSwap(_tokenIn, _tokenOut, _amountIn) {
    if (!this.contracts.kpxRouter) throw new Error('kpxRouter address not configured');
    throw new Error('estimateSwap — KPXRouterGateway quoting not yet deployed (Phase 5)');
  }
}

module.exports = { AxioledgerSDK, ANS_TLDS, DEFAULT_RPC };
